### ISSUE TITLE
Test Mode does not work or run when AdMob is added

### ISSUE THREAD

**Issue by Spellytics** [FlutterFlow/flutterflow-issues#1002]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It's just stuck at loading when you add admob banner into the app, but it works fine in production. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70740500/a99ddc6d-a376-4d74-abd2-0480948ee13f)

### Expected Behavior

Test Mode works when AdMob banner is added

### Steps to Reproduce

1. Configure AdMob in App
2. Add AdMob Banner
3. Run in Test Mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfksmAsJR1m8tK7q6JcsFGnjsvQm0cTIMziNZ+exUbfaL1Buwce8zRM01oTunmaVNcAFX8r3Mx0N7SieGSKMIoHyqAftl/1LhyYTnee2igaZCMPZOKZHB7HcZUCBGx57uC3Al4OslYWE4a6jm6Au6/QnTDIuu/Zwh9f6PHaOI=

### Context

I'm trying to put an ad banner on my home page.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/70740500/a99ddc6d-a376-4d74-abd2-0480948ee13f)

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: Web
- Browser name and version: Chrome Version 114.0.5735.134 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by bulgariamitko** [comment]
I think this is normal because the package will only work for mobile. See details 
https://pub.dev/packages/admob_flutter

This is a documentation request as it should be written in the Test/Run mode that you can't test AdMob there.

**Comment by Spellytics** [comment]
@bulgariamitko 
I strongly disagree. 
This is not a case of just documentation.

It basically mean that you cannot use **Test/Run mode** at all for the whole app if you want to use Ad Mob (regardless of which screen the widget was put in). Then, why do we have this as an option for integration with Flutterflow? Additionally, there is a toggle to use 'Test Ad' in Flutterflow. It's clearly intended for Flutterflow to integrate Ad Mob. 

This means that as a user I can either not use Ad Mob at all or not use Flutterflow any longer for development.

**Comment by agreaves** [comment]
Hi @Spellytics, thanks for the bug report! @bulgariamitko is correct that this is because AdMob is only supported on mobile, however you're absolutely right that this should not prevent you from running on Web / Test mode. I'll make a change to show a placeholder instead when running in run/test mode, which should be fixed in the next release.

In the meantime, I'd recommend adding Conditional Visibility on the AdMob widget to show only when `!isWeb`. If your app is intended for Web as well, I'd recommend doing this in general.

**Comment by TheScriptingVajra** [comment]
This issue is still present as of today.  Test mode doesn't load in browser after adding adbanner. Even if visibility set to off, it doesn't load.
