### ISSUE TITLE
empty Supabase result set causes a 406 Error

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1131]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If you use a supabase query to return a single row and the result set is empty, this causes a 406 error.

Postgres will return:

 {"code":"PGRST116","details":"Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row","hint":null,"message":"JSON object requested, multiple (or no) rows returned"}

### Expected Behavior

For the error to be trapped and a 406 is not thrown, but the result set being empty.

Ideally it would be good to have the property "Row Exists" in the same way as Firebase has "Document Exists"

### Steps to Reproduce

Call a Supabase query  for a single row, that returns empty results

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

checking if a record in one table exists in another.  

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/e927285e-39c6-4137-bcfe-57adf62304a9)
Causes a 406 error

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by kevintonb** [comment]
Hey @OldFred2023 , can you please provide clearer additional reproducible steps for this issue? Please also feel free to recreate the bug in a new blank project and share the bug report code here in the thread! :)

**Comment by OldFred2023** [comment]
Hi, I kind of thought it was self explanatory, call any supabase query that expects a single row, and set the filter to something that will return null results, such as selecting an Id that doesn't exist.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/4a95484e-81a3-486b-81f3-d388bf56a05c)

I have recreated it for you in a test project, here is the bug report, but it is easy to reproduce in a matter of minutes.

ITESz/Hqx89gocBH7pDMbMFAhQIgQ0QnU7gnlO1ucx40GJCvPaQEYcnRYUNKTs+AfFdmB1L9mmQFpd3Gj+z9EfQ5Cymtb4Bd0JVATwr/ZGGgeLqqDJbhdnx6P95YGHKg1sKskRZ/Iu9fV11g7DqhNq3qNleeY8aSfxBlZ7vfcPo=

**Comment by OldFred2023** [comment]
Blank project has been created, with bug report, steps to reproduce have been stated, so why hasn't this been triaged?

**Comment by OldFred2023** [comment]
Bump!

**Comment by OldFred2023** [comment]
Its been 3 weeks and not a single response from FF

**Comment by OldFred2023** [comment]
@hariprasadms You seem to be the most active here in supporting the user base and investigating the issues we face, is it possible you could look at this as there has been no activity on this issue for over 3 weeks?

**Comment by OldFred2023** [comment]
Nudge!

**Comment by RusDyn** [comment]
I'm facing the same issue. 
It's endless loading widget in my case

**Comment by OldFred2023** [comment]
its been 6 weeks and no feedback from FF.... Why are you ignoring issues?

**Comment by OldFred2023** [comment]
@agreaves - its been 6 weeks and no feedback from FF.... Why are FF Team ignoring issues?

**Comment by jonathan-launch-technology** [comment]
Is there a workaround for this? I am new to FlutterFlow and trying to wrap my head around error handling. If I want to run a single row query which may sometimes return no results, is there a mechanism for me to handle the 0 record use case? Or am I expected to always have queries that return one record?

**Comment by simonfrance** [comment]
Same problem here... there shouldn't be any error when you get no result from a single-row request...

Only way around it : make a regular query (not single row), put the result limit to 1, check length of result (should be 1 if a result, 0 otherwise), and use the get Specific Item / First Item in Flutterflow to get the data... 

This basically remove the benefits of having this "Single Row" option in FF... but allow it to work...

**Comment by starwaver** [comment]
bump

**Comment by agreaves** [comment]
Hi @OldFred2023 and everyone else. I'm so sorry this issue slipped through the cracks, it seems like a serious bug. I'm currently looking into it (will try to reproduce) and will hopefully have a fix for the next release.

**Comment by dansomrack** [comment]
I am hitting this issue as well. I am trying to build a page that is conditional on a row being in the table. If the row is not there, it just hits the 406 error.

In short. the condition of a single row doesn't work for Supabase, if the row is not there the app will spin forever. 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/11216609/e4cdc813-ffee-46cf-b847-060cb9647edd)

It seems like the workaround is to request a list of rows and then use first index in the list.

**Comment by agreaves** [comment]
Hi @OldFred2023, the strange thing is the issue does not occur when run locally, but I do see it in Test mode. Regardless, I'm adding a `catchError` in order to gracefully handle the error and simply return an empty list when this occurs. So this issue should be fixed next release!

**Comment by simonfrance** [comment]
I am still seeing this error... Can you tell us when this fix will be in production ?

**Comment by ErencanPelin** [comment]
I am also still seeing this error when trying to query a list of rows as well. Same error, endless loading widget - empty list widget does not appear.

**Comment by splashingwholefear** [comment]
@agreaves 
Still have this problem on v4.0 - Flutter 3.13.7.
It may helpful if there was "Row Exists" property when passing result of query's field to a custom function as argument, because it causes error even if the argument declared nullable.

> Ideally it would be good to have the property "Row Exists" in the same way as Firebase has "Document Exists"

**Comment by OldFred2023** [comment]
still happening for me, and causing stability issues, needs resolving asap.

**Comment by OldFred2023** [comment]
@agreaves This is still causing stability issues in Apps, please can you re-open this and ensure it gets fixed please.

**Comment by OldFred2023** [comment]
> Hi @OldFred2023, the strange thing is the issue does not occur when run locally, but I do see it in Test mode. Regardless, I'm adding a `catchError` in order to gracefully handle the error and simply return an empty list when this occurs. So this issue should be fixed next release!

@agreaves This is still causing stability issues in Apps, please can you re-open this and ensure it gets fixed please.
