### ISSUE TITLE
Flutterflow reverting when i make new changes 

### ISSUE THREAD

**Issue by diddytrippz** [FlutterFlow/flutterflow-issues#1303]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when I make new changes on my app it keeps on reverting back and cancelling new changes

### Expected Behavior

I expect the changes i make to be saved 

### Steps to Reproduce

When you make any changes to your app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

I’m updating my app and I manually have to save every change i make. i.e adding a new widget or changing text color

### Visual documentation

N/A

### Additional Info

N/A

### Environment

```markdown
- FlutterFlow version: 1.1.97
- Platform:MacOs App
- Browser name and version:
- Operating system and version affected: MacOS Monterey 12.6
```

**Comment by jasminder** [comment]
This is serious issue. We are working on a very complex app and changes are just vanishing. 
Please resolve it on urgent basis.

**Comment by idea-garage** [comment]
It's terrible for us, preventing to develop trusted application. Please resolve urgent.

**Comment by agreaves** [comment]
Hi all, sorry you're experiencing these issues. We've recently identified what we think was the cause and fixed it a few hours ago (you may need to refresh the page in order to be up to date with the fix).

In the meantime, can everyone please include a [Bug Report Code](https://docs.flutterflow.io/widgets-and-components/widgets#get-bug-report-code) so that I can further investigate the issue and verify that it's the same issue we identified? Also, please let me know if you are still actively experiencing this issue as it will let me know whether the fix has worked.

**Comment by TimurKr** [comment]
Hi @agreaves. 

I am using mac desktop app and am still experiencing this. I restarted and even redownloaded the app. 

I also tried working in the web app for a couple of minutes and in that time I haven't noticed any issue, but I preffer the mac app as it performs much better and with less lag. Maybe the fix worked and it just haven't been pushed to the mac app? Thanks for looking into this, because the app is virtually unusable with this bug. 

Here is a bug report from a very simple component, where when I rewrote one of the texts, it reverted back to the original text multiple times. 

```IT4ohfHqw81NocNc+KrAacFvvyQUKWJ+ULso18pBazwbfe+uB4kqevfOTERWOe2hTVFAMFn8gWoW3M7ojYaTUMEBIRCYQJhBzKtQZg7vUnmgaYyvFJWvPXBBO8djIGq607TR2RJ/JrRvS14Yw2C2O96XbHfAJr37IjAwDa/LZO4=```

**Comment by MohitKandu25** [comment]
Hi @agreaves. The issue is still there. It becomes much worse when working with multiple members. In my project we have 2 people with teams membership. When I'm the only one working, the project feels more responsive and I barely have the changes reverting (although it's still there). 
In console log, this is what I see. Do you think these could be a reason, especially the one that says exhausted maximum allowed query writes? 
![reverting_issue_logs](https://github.com/FlutterFlow/flutterflow-issues/assets/104911624/69f77841-3492-40ce-bb39-f03290268f23)

**Comment by agreaves** [comment]
Hi @TimurKr, thanks for the response and bug report code. The push has not been applied to MacOS yet so that explains why you are still experiencing issues. I will deploy the fix to MacOS later today.

@MohitKandu25, could you please share a [Bug Report Code](https://docs.flutterflow.io/widgets-and-components/widgets#get-bug-report-code) to help me investigate. Please make sure you and your collaborators both refresh and are on the latest version of FlutterFlow. Thanks.

**Comment by MohitKandu25** [comment]
Hi @agreaves. I can assure you that we both are on latest version of FlutterFlow. Here is the bug report code where the revert issue occurred last:
IT4Oj8nf5c9NoctD+KX2dcdB/WEWMjo4RLxMm+tuc0sgfIPNG4gIZfTBXE9uOP25dkFqfE2ggn4z0//Hm9z1VPFeCw+bY4BHzs9UdDzyeFGlb5SkPKuoQ2hUGshVIXad157YvBUnPvdYclIMwU2AHO6sVhftHqbyPDAdM/mXIqjXvgfuQ0SLb3kNh1JWeC/v

**Comment by jasminder** [comment]
Revert has started happening again on web.

IT4Oksjf35N2seFc+Kr2b8BKpyQ7GDo3RIZMjetTd0gcJZ/NGogUY8jeVERBXubnS2w7JmG0r2oW0vzpvePLM8BcGAesfpxZzc9AEg/KcF2RbpDQFJWgdXBRP+hmN2q95p6vphF7OrZoLlIB212ACuuyZC/fQKbNNVQ0Da/LZO4=

**Comment by agreaves** [comment]
@jasminder Would you mind describing exactly what you're encountering with the reverting? A screen recording would be most ideal but I need some sort of description of what was lost and how (collaborating or working solo, etc.). Thanks!

**Comment by jasminder** [comment]
@agreaves 
https://www.awesomescreenshot.com/video/20223387?key=915bd67646c8df631576a9650dc4314c
After recording this one, a lot major reverts happened. 
I am working in a collaboration for this project.

**Comment by fillipe-oliveira** [comment]
Im having this issue as well.

The system keep reverting every 3 actions i make.

**Comment by agreaves** [comment]
@fillipe-oliveira Can you capture any screenshot or recording of the event? Or provide a bug report code and an approximate time of the event? The more specific the better.

@jasminder I appreciate the information, I'd ask the same if you're able to provide. We made one large fix (mentioned above) and a few minor fixes that might be the source, but still trying to diagnose the issue you all may be running into.

**Comment by agreaves** [comment]
I've applied what should be a fix to this issue! Apologies for jumping the gun earlier.

Please let me know if the issue continues, I'll continue to listen to reports and verify that the issue is fixed.

**Comment by jasminder** [comment]
@agreaves 
Thanks. We are now testing, will report EOD.

**Comment by efficientaman** [comment]
@agreaves seems to be working fine from yesterday. Thanks!

**Comment by agreaves** [comment]
Going to cautiously close this issue now, but please let me know if the issue arises again!

**Comment by smn-snkl** [comment]
Still having the same issue. We've been having this for over a month now, especially experiencing it the more people are working on the project at the same time. I definitely don't have multiple windows or anything open with the same account.

Most recent bug report code: IT4gl8/luI9Oj7xZ7aryLO9Vq2IWNU9+apc0rNlud0wdCePwEYYTP8z4bRBBWOqHeXxUGVCWkk4d//yPiITTNfI7PSqYY7k61KpTUxDvUly6aJimOru8WXJAGcpMJhGuyLS7sBVRNtphLWAg7WGMOtm+b3qCf9qOYwx5e6fDbOY=

Also recorded a video including the DevTools console showing now errors at all, but changes still disappearing after refreshing:

https://github.com/FlutterFlow/flutterflow-issues/assets/11544327/c34ae525-a0ea-4012-a7a6-ea25772232b5

I also believe the changes are just not saved at all, because even when pushing to GitHub right after making the change, the change is not available on the repo. It's like this change is just stored in the browser but never makes it to the backend.

**Comment by alexruimy** [comment]
> I also believe the changes are just not saved at all, because even when pushing to GitHub right after making the change, the change is not available on the repo. It's like this change is just stored in the browser but never makes it to the backend.

I am also having this issue and I agree with this assessment.

Looking through the forums and issues posted here, this is _clearly_ happening regularly to a number of users. Losing work is simply not acceptable, and seeing these issues closed is very frustrating. This should be FF's top priority.

**Comment by Sergii-Shpak-072422** [comment]
I have the same issue. I developing a web app and use the Brave browser. I started noticing that the changes have not been saved. It is very frustrating, especially as I am working on the client's project.

**Comment by bulgariamitko** [comment]
I have the same issue. My work keep on disappearing when working on a project with multiple users.

**Comment by Luke-Alchin** [comment]
I am also having this issue. It has happened multiple times where a FF expert and I are losing work, which seems to be reverting, and we are working on top. We are both very diligent with saving and versions, and we are also not working on the project at the same time together to try and avoid this. It has become a costly issue.

**Comment by will4381** [comment]
I just posted a bug having the same issue but inside of the custom widget "IDE". I remove code and paste in new code and it wont let me save upon refresh it simply reverts back to the old code. No way to save or make any progress. Tried in different browsers, cleared cookies, and tried on the Mac app. Nothing works, just started happening out of no where

**Comment by agreaves** [comment]
Hi all, reopening this issue as it seems to still be occurring. Apologies for the frustrating experience, losing works is indeed unacceptable.

However, in order to fix I'll need as much information as possible. There's not been a straightforward explanation we've found, and it can vary depending on browser / number of collaborators / whether on a team etc.

@alexruimy @Sergii-Shpak-072422 @Luke-Alchin @will4381 Could you please all provide me with the following:

- The Bug Report Code (this gives me the project link, as well as some other useful information)
- What type of work tends to be lost? Is it specific (e.g. always custom code) or just general.
- What browser are you using?
- Does it occur while multiple people are collaborating or even while working independently?

With that information, I can re-open investigation into this issue of lost work. I hope to get to the bottom of this as soon as possible, because as mentioned losing work is unacceptable. Any and all information you can provide to this end would help quite a bit! Thanks.

**Comment by Sergii-Shpak-072422** [comment]
- I have lost actions, formatting of numbers, and custom functions. 
- I worked in Brave and macOS app. I am sure that I lost work in Brave but not sure about the macOS app. 
- I work alone in the app on the Professional plan.

**Comment by will4381** [comment]
I do have memebers on my plan but they were not working on it when I experienced this issue. I have only experienced it with custom code. I am using Safari, but also tested it on Chrome as well as the Mac app, tried clearing cookies in both browers as well, the issue still persisted. This is the first time I have experienced this problem outside of switching from FlutterFlow web to FlutterFlow desktop, which is reasonable unlike this issue. I dont have a specific set of steps that caused it, I had been deleting, copying, and pasting large amounts of code out of the custom widget builder, before it started occuring.

I attched a drive link with a screen recording of the issue: https://drive.google.com/file/d/1oTTPVxXlbqEEtp9m8EBIzRn5hJfw-8oQ/view?usp=sharing

**Comment by agreaves** [comment]
@Sergii-Shpak-072422 @will4381 Thank you for the information. Could you please include the Bug Report Code to help me further investigate?

**Comment by will4381** [comment]
Here is bug report code: IT4khc/1z892xPVA7rrtbflVlWEsKWU3TL03pu0bFEggGLbrBIYMacjRdhZoXbDnYAk2KEWGuGAC096Jv4fiFfoFCwWCfYhez8xTWwryRl2/aoS2DKq3OXJ6QO9mGmnF5Lu3qhVSIvRYdU5n2E+ECuyucDbsJ7H4Zwh9f6PHaOI=

**Comment by idea-garage** [comment]
One Possibility:
If you work in multiple browser tabs or windows, you may be reverted to the past, so please check each one.

**Comment by will4381** [comment]
@idea-garage I thought so as well but tried a thousand times reloading making sure other versions of app were closed to no avail

**Comment by will4381** [comment]
@agreaves upon some more testing it appears to revert the code but maintain the new imports when copy and pasting custom coded widgets. Outlined in the video https://drive.google.com/file/d/1Z0fKvrYXFoO-EzRyE_XU7UR6pAoOPoG-/view?usp=sharing

**Comment by Luke-Alchin** [comment]
@agreaves Hi, we have experienced loss when working on a project without realising this has reverted to a previous save or version, and we have worked over the top. You see, in this scenario, it's then challenging, almost impossible to recover. 

We are diligent with versions, not working multiple tabs and not working on a project simultaneously now, especially after experiencing loss. Though, it has kept happening.

We are saving versions before and after starting any work to add redundancy to our workflow. And once again, only one person is in the project at one time.

Maybe @bulgariamitko can explain some detail where his workflow may differ.

I can't send the bug report code because I am still waiting for a response from FF support if that's how it is attained.

In my case, I am working with FF expert @bulgariamitko in a commercial arrangement. Having to do rework does make this challenging for both parties.

If there is some procedure or workflow that could help mitigate this issue, it would be helpful because, at this stage, we cannot determine the cause. It does affect the commercial viability of the platform to the extent that loss has now caused us to hold a project until we can resolve the issue to mitigate the expense of rework. 

Please let me know what other information might be helpful, I am happy to oblige in any way I can.

**Comment by will4381** [comment]
@Luke-Alchin Right click on widget in widget tree and from the dropdown select generate bug report code

**Comment by Luke-Alchin** [comment]
> @Luke-Alchin Right click on widget in widget tree and from the dropdown select generate bug report code

Cheers

**Comment by Luke-Alchin** [comment]
@will4381 Cheers

**Comment by Sergii-Shpak-072422** [comment]
Here is the bug code of one of the impacted widgets ITFTzufq24Z1rupJ+KrUdMZsmio6I0MBX5Ir1utvGAoYJYCtE5olPsnEaXdCTNOEeVdMIE2Z/T4G7sLNjezlA/cEJUybfKV607pIZg7hfEOXabnWEZe8ZGtAJ/xXCmqY37TYsyRQCNRtSGRn3U+Lcq3qNleeY8aSfxBlZ7vfcPo=

**Comment by bulgariamitko** [comment]
@agreaves 

to answer your question form my perspective. The custom code is still there, but I think it is because I haven't wrote any custom code when I was building this particular section of the project.  There are many widget and functionality that is missing it is like working with the project and then save a new version and then the entire version is gone like the whole working session is gone, around 3-4 hours of work. I am talking about Actions, Widget logic like conditional visibility, Veritable condition like if/then/else, change of a widget from contender to image for example and much more.

Here is just one of the examples in which I have lost my whole logic of displaying a map marker in which I have the marker and initial location as if/then/else condition (the whole condition was gone), all Actions related to the map were gone and a page parameter was gone, basically everything I did in the saved version. Here is more info about this Widget I have choose

The Bug Report Code (this gives me the project link, as well as some other useful information)
IT4whvHlz4xgodtF7s/UbPlR/WI4Ijs8RK8vju5TaCs8JL7oPOwifPfDN0pvTL3iSm9UfFn8+WEd/Pfqkd/uV8BeNSuaba5nzLVxWzv/eHy5Va7SOrizfW1REe5jfXKb0KargR1QCOpqLSQs7XGEGdmWbDPvQbqxOzBFD/G1JdeK2SrDX1iXc2URm05KZDPz


What type of work tends to be lost? Is it specific (e.g. always custom code) or just general.
In this case it is the variable value and also inside this widget there is a stack with an icon which had a conditional logic which was gone as well.

What browser are you using?
Latest version of Chrome

Does it occur while multiple people are collaborating or even while working independently?
It occur when I am working independently. 

I have notice that almost every time I visit the project this message appears 
![Real-Engine-V1-FlutterFlow (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/7221384/d93ade2b-7050-4747-a8ae-8a3736826a22)

I don't know if there is a connection, but I feel like if you do not update the page (which I always do) and start building and just ignore the message it will override lat changes, I am not sure if I am right I am just saying what I am thinking.

**Comment by Sergii-Shpak-072422** [comment]
One more observation of this bug. Yesterday I changed the credentials in an API call (URL, API key) and these changes were not saved when I navigated from the project editor to the list of projects in my account. 
What seems to work for me to overcome this bug - after every change I manually create a named version of the app.

**Comment by will4381** [comment]
@agreaves any updates or more info you need? Not being able to add new custom code really putting a stint in my project, happy to work with you on whatever you need to get this figured out and fixed

**Comment by agreaves** [comment]
Hi @will4381, I've still not been able to reproduce this, which has made it a bit difficult to debug. But I'm still actively investigating. In general, the more specific details anyone can provide the better.

Your case seems rather interesting though, not being able to add custom code at all is rather unusual. Would you mind creating another more detailed screen recording of the issue at hand? Perhaps narrating (or describing in text) exactly what you were trying to do and what went wrong? I'd like to take a deep dive into your specific project and get to the bottom of the issue (at least in your case).

**Comment by will4381** [comment]
Hey @agreaves heres a video with some narration to better explain hopefully. I did talk with chat in app and Danny mentioned he could edit the code on his device no problem. But despite changing browsers, clearing cache, cookies, still doesnt work. And using another device isnt quite feasible for me. Here is video: https://drive.google.com/file/d/16KA02SauUki5o9QwX2gvSdVCPGB_8tqq/view?usp=sharing

**Comment by agreaves** [comment]
The primary fix for this issue is now live! Please let me know if you continue to experience any issues.

@beefixi Can you share the bug report code for your project so I can investigate? It may be a different problem.

**Comment by will4381** [comment]
Hey @agreaves, 

Was excited to hear the news of the fix being live, however the issue with my project still persists, although it was slightly different from what others were experiencing. I recorded a video with narration to showcase the problem, in the new version. Willing to do whatever you need to get this squared away, really putting a stint in my current project. 

https://drive.google.com/file/d/1S2UQqnYkOI4s9yfrCs3Y-MyGIj9LKLGR/view?usp=sharing

New Bug Report Code: IT4khc/1z892xPVA7rrtbflVlWEsKWU3TL03pu0bFEggGLbrBIYMaeOlQE9tYN/iYH9lKEWIgkgCpNLeidr+GPJeExyZb4RA+qgJWzqXbGO/aoS2DKq3OXJ6QO9mGmnF5Lu3qhVSIvRYdU5n2E+ECuyucDbsJ7H4Zwh9f6PHaOI=

**Comment by beefixi** [comment]
> The primary fix for this issue is now live! Please let me know if you continue to experience any issues.
> 
> @beefixi Can you share the bug report code for your project so I can investigate? It may be a different problem.

nothing changed, still experiencing the same issue. Doesn't save custom widgets.

**Comment by will4381** [comment]
@beefixi right-click widget in widget tree and select option "Generate bug report code"

**Comment by agreaves** [comment]
@will4381 and @beefixi this seems to be the same issue. Still investigating but I'm confident I'll be able to track down and fix it with the available information.

**Comment by will4381** [comment]
@agreaves I also had posted another thread as this one didnt quite apply to me at the time:

https://github.com/FlutterFlow/flutterflow-issues/issues/1879

Another user there was experiencing as well, I dont know if you want to reach out to him, but he might have some info as well.

Thanks for taking the time to reply and get to the bottom of this, really means a lot!

**Comment by agreaves** [comment]
Thanks for the heads up. As a final point, this is only happening in one particular widget correct?

**Comment by will4381** [comment]
@agreaves I havent tested if I can create custom widgets with differing code, but issue persists everytime whether I create a new widget, rename a widget, etc. This is showcased well in the video here (https://drive.google.com/file/d/1S2UQqnYkOI4s9yfrCs3Y-MyGIj9LKLGR/view?usp=sharing) that I delete and remake the custom widget and the issue persists. Seems to be the editor, I'll also attach the code for the widget if that would cause some sort of error, but it did seem to work when testing in another project.

`// Automatic FlutterFlow imports
import '/backend/backend.dart';
import '/backend/schema/structs/index.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

import '/custom_code/widgets/index.dart';
import '/flutter_flow/custom_functions.dart';

import 'package:intl/intl.dart';
import 'dart:async';
import 'dart:math';
import 'package:syncfusion_flutter_charts/charts.dart';

class StripeChart extends StatefulWidget {
  const StripeChart({
    Key? key,
    this.width,
    this.height,
    this.stripeData,
    this.range,
    this.intervalType,
  }) : super(key: key);

  final double? width;
  final double? height;
  final List<StripeDataRecord>? stripeData;
  final String? intervalType;
  final int? range;

  @override
  _StripeChartState createState() => _StripeChartState();
}

class _StripeChartState extends State<StripeChart> {
  UniqueKey _chartKey = UniqueKey();

  @override
  void didUpdateWidget(covariant StripeChart oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.range != oldWidget.range || widget.intervalType != oldWidget.intervalType) {
      setState(() {
        _chartKey = UniqueKey();
      });
    }
  }

  DateTime _getFirstDayOfWeek(DateTime dateTime) {
    int currentDayOfWeek = dateTime.weekday;
    int daysToSubtract = currentDayOfWeek - DateTime.monday;
    return dateTime.subtract(Duration(days: daysToSubtract));
  }

  DateTime _getAdjustedMinimum(DateTime calculatedMinimum, List<StripeDataRecord>? data) {
    if (data == null || data.isEmpty) return calculatedMinimum;
    var timestamps = data
        .map((record) => record.timestamp)
        .where((date) => date != null)
        .cast<DateTime>();
    if (timestamps.isEmpty) return calculatedMinimum;
    DateTime earliestDataDate = timestamps.reduce((a, b) => a.isBefore(b) ? a : b);
    return earliestDataDate.isBefore(calculatedMinimum) ? earliestDataDate : calculatedMinimum;
  }

  DateTime _getMinimum(int? range, String? intervalType, List<StripeDataRecord>? data) {
    DateTime now = DateTime.now();
    DateTime calculatedMinimum = now; // Default to 'now', adjust as needed
    if (intervalType == 'Today') {
      calculatedMinimum = DateTime(now.year, now.month, now.day);
    } else if (intervalType == 'Yesterday') {
      calculatedMinimum = DateTime(now.year, now.month, now.day - 1);
    } else if (intervalType == 'This week') {
      calculatedMinimum = _getFirstDayOfWeek(now);
    } else if (intervalType == 'Last week') {
      calculatedMinimum = _getFirstDayOfWeek(now).subtract(Duration(days: 7));
    } else if (range == 12 && intervalType == 'Last 12 Months') {
      calculatedMinimum = now.subtract(Duration(days: 365));
    } else if (range == 90 && intervalType == 'Last 90 Days') {
      calculatedMinimum = now.subtract(Duration(days: 90));
    } else if (range == 30 && intervalType == 'Last 30 Days') {
      calculatedMinimum = now.subtract(Duration(days: 30));
    }
    return _getAdjustedMinimum(calculatedMinimum, widget.stripeData);
  }

  List<ChartSeries<StripeDataRecord, DateTime>> _getLineSeries() {
    return <ChartSeries<StripeDataRecord, DateTime>>[
      SplineSeries<StripeDataRecord, DateTime>(
        dataSource: widget.stripeData ?? [],
        xValueMapper: (StripeDataRecord data, _) => data.timestamp,
        yValueMapper: (StripeDataRecord data, _) => data.balanceAmount,
        name: 'Balance Amount',
        animationDuration: 2500,
        splineType: SplineType.monotonic,
      ),
      SplineSeries<StripeDataRecord, DateTime>(
        dataSource: widget.stripeData ?? [],
        xValueMapper: (StripeDataRecord data, _) => data.timestamp,
        yValueMapper: (StripeDataRecord data, _) => data.pendingAmount,
        name: 'Pending Amount',
        animationDuration: 2500,
        splineType: SplineType.monotonic,
      ),
    ];
  }

  @override
  Widget build(BuildContext context) {
    DateTime visibleMinimum = _getMinimum(widget.range, widget.intervalType, widget.stripeData);
    DateTime visibleMaximum = visibleMinimum.add(Duration(days: 6)); // Assuming 7 days for a week

    return ClipRect(
      child: SfCartesianChart(
        key: _chartKey,
        plotAreaBorderWidth: 0,
        primaryXAxis: DateTimeAxis(
          intervalType: DateTimeIntervalType.days,
          interval: 1,
          dateFormat: DateFormat('MM/dd/yyyy'),
          visibleMinimum: visibleMinimum,
          visibleMaximum: visibleMaximum,
        ),
        primaryYAxis: NumericAxis(
          majorTickLines: MajorTickLines(color: Colors.transparent),
          axisLine: AxisLine(width: 0),
        ),
        series: _getLineSeries(),
        trackballBehavior: TrackballBehavior(
          enable: true,
          lineType: TrackballLineType.vertical,
          activationMode: ActivationMode.singleTap,
          tooltipSettings: InteractiveTooltip(enable: true),
          tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
          shouldAlwaysShow: false, // Adjusted to hide the marker dots
        ),
      ),
    );
  }
}
`

**Comment by beefixi** [comment]
> @beefixi right-click widget in widget tree and select option "Generate bug report code"

Hi Alex, I couldn't generate a bug report from the custom widget tree, there is no right-click in the widget tree, but I could do it from the page tree: IT5TlvHl3It2m+EE1a6Jc8FFoDwXH1s7bZIrmOtuTQ0jNuvyE+wiO+DSU3FJXMu4d2xUJGH8sGAIps2Mv87yFfo4OkyIQ75P1ah2YAmXYH2lb7bRCarpQ3x8TOZWIH7F4LCOiiYlPshsdEI82UOMJumsSgjAQ+fADlQjJeWKCKPNp2iUFSXjFThQtmNecCfn

This is not only one widget or one particular page, it's related to all custom widgets, I cannot save any changes or create a new one, it creates or saves, but when I refresh the web page it disappears all my changes or new widgets. 

Also, maybe will be helpful: when I duplicate an entire project and try to save or make changes/create new custom widgets everything is ok, and works as expected, it's only an issue with one particular project, with another project in my account I don't have this issue, so it's only one particular project and I noticed this issue on December 4.

**Comment by beefixi** [comment]
any resolution? when is it gonna be resolved? Our project is stuck and delayed because of this issue. How can we resolve it ASAP? Why is there no resolution for almost two weeks?

**Comment by agreaves** [comment]
Hi @beefixi, sorry it's taken a long time to resolve. I simply haven't been able to reproduce the issue. I was able to make one small fix which may or may not fix it - this will be released tomorrow. However, I'm not sure it's what's causing issues with your project.

If you're comfortable with it, let me know if you'd be willing to add me as a collaborator to your project. I've seen the support chat we have going, so I could send you the appropriate email to add there. This would be by far the easiest way to reproduce and fix the issue if tomorrow's fix does not work. Please let me know! And thanks for your patience, hoping to fix this quickly!

**Comment by beefixi** [comment]
looks like it's resolved, thank you so much!!!

**Comment by will4381** [comment]
@agreaves issue also seems to be resolved for myself as well, outside of syncfusion charts no longer working. Previous snapshots that published successfully no return errors relating to text scaler.

 Thanks so much for the help on the custom code issue though!

**Comment by Josefpa** [comment]
> Still having the same issue. We've been having this for over a month now, especially experiencing it the more people are working on the project at the same time. I definitely don't have multiple windows or anything open with the same account.
> 
> Most recent bug report code: IT4gl8/luI9Oj7xZ7aryLO9Vq2IWNU9+apc0rNlud0wdCePwEYYTP8z4bRBBWOqHeXxUGVCWkk4d//yPiITTNfI7PSqYY7k61KpTUxDvUly6aJimOru8WXJAGcpMJhGuyLS7sBVRNtphLWAg7WGMOtm+b3qCf9qOYwx5e6fDbOY=
> 
> Also recorded a video including the DevTools console showing now errors at all, but changes still disappearing after refreshing:
> 
>  FF_Reverting_Changes.mp4 
> I also believe the changes are just not saved at all, because even when pushing to GitHub right after making the change, the change is not available on the repo. It's like this change is just stored in the browser but never makes it to the backend.

Yes have been noticing this recently, it takes like 2 pushes to get the update I just made sometimes?

**Comment by agreaves** [comment]
So glad to hear that!

**Comment by chris-PearlIT** [comment]
@agreaves I'd like to re-open this thread as unresolved.
We are currently working on a project using FF v4.0.
development has been taking place today in browser on a windows PC.
However my developer stopped working on it today at around 14:09.
I, as dev lead, signed into the project on my iPad Pro 12.9, to check progress.
iPad is using OS v 17.2
FF App version 4.1.18
The project has now reverted back to where it was the last time I logged in with the iPad two days ago. The project log shows myself making an update today at 16:02 where no changes were made, I just logged in to look.
Behavior suggests the repository has been dumped in favor of the version on my iPad.
I want to say this issue is urgent but in reality without the function to remove the updates that were made at 16:02, it's **grave**,
If the main branch version can't keep itself correctly updated across all platforms then we are paying developers to do their work twice.


![Screenshot 2024-01-04 165156](https://github.com/FlutterFlow/flutterflow-issues/assets/97460439/ec568998-790c-499f-918f-9587076a477e)

**Comment by ch-muhammad-adil** [comment]
@agreaves I would keep this thread here because this is not resolved, I am badly stuck on our project. I have shared all details with @krino (Technical Support) I have shown them videos and everything.I have been struggling with the project for past 8-9 hours, where writing one action has caused whole problem when i tried to use it. My internet might be slow at that time when I was working and code analyser was failing too, but reverting back to previous version still not helped.  

To me action was writing with proper standards and had no problem, all of sudden my project started showing a lot of errors, I then reverted to previous version, where my errors were gone I have even saved that to new version, It runs fine but never sync with github because it says it is having errors.  As soon as I refresh my browser page those errors start showing up again. Now I have roughly 200 errors and resolving them is difficult. I noticed the issue happens because of Authenticated User reference is not available in the app. I cleared browser cache and tried many other ways but nothing is happening here. Something relevant to FirebaseAuth may be because that is one thing I have been using in action. 

<img width="1233" alt="Screenshot 2024-01-10 at 5 47 11 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8264639/f5187f7b-6888-4999-ba75-bece0bffa22f">


I can send link to video for what I am witnessing if you share your email or may be some other medium of communication..

**Comment by flutterflowdevs** [comment]
@agreaves , @bulgariamitko 
Please re-open this issue.
I am currently working on FF 4.0 - Flutter 3.13.7.
Today, I have started facing this issue very frequently. FF is reverting my code very frequently. 
I am building a complex app and because of this behavior I am taking too much time to debug the issue. 
Please help us regarding this.

**Comment by bgagandeep** [comment]
Same issue here.... Working on an app for over 18 hours at a stretch only for the entire function to get reset.

**Comment by g4sser** [comment]
Guys, all of the project changes are just gone. This sucks. For me, FF is not trustworthy with this issue.

**Comment by sabatage3** [comment]
The problem persists, and it's worse than before. It usually deletes translations, but lately, it's been deleting queries that I had copied and pasted back. However, upon pasting the query back, it had disappeared. Today, it just wiped out an ENTIRE PAGE!! This is catastrophic. It's impossible to use FlutterFlow if it keeps deleting the changes we make. This bug must be the #1 priority for the development team. Forget about new widgets and new versions until this serious issue is resolved. We can't have translations, changes, or pages disappearing anymore. Please @SameerShahzad99, this is the worst bug ever

**Comment by Nickman87** [comment]
Opening my project on the desktop client reverted a whole day of changes, luckily I had a snapshot to revert to.
If this keeps happening, FF will end up in the trashpile...

**Comment by earlgreycoder** [comment]
Unfortunately this saving/reverting changes issue appears to be happening to me in december 2024. 

https://github.com/user-attachments/assets/1dc62400-cda5-4e69-8d73-e797db98a7c6

**Comment by KaRaOkE18** [comment]
I also encounter the reverting issue for a page i did not touch since a recent update. It mentions layout errors even tough I did not change anything. The thing is, I can't change anything or fix since every change is reverted instantly. 

I can't do any deploy until this is fixed! Please help:(
[Screen Recording 2024-12-23 at 10.14.27.zip](https://github.com/user-attachments/files/18227689/Screen.Recording.2024-12-23.at.10.14.27.zip)

Edit: I can't even save the components somewhere else and fix the error on a new page.
