### ISSUE TITLE
Google login does work in "test mode" but not in "run mode"

### ISSUE THREAD

**Issue by frank-bee** [FlutterFlow/flutterflow-issues#1489]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If - in run mode - I click on the goole login button, there is an exception thrown.
```
main.dart.js:32961 Uncaught TypeError: J.cc(...).ac is not a function
at Object.fc (main.dart.js:32961:24)
at Object.cW (main.dart.js:5023:3)
at b1W.$1 (main.dart.js:49727:19)
at c2V (main.dart.js:3139:17)
at main.dart.js:3147:51
```

or 

```
main.dart.js:3058 Uncaught TypeError: Cannot read properties of undefined (reading 'mE')
at Object.bcx (main.dart.js:33034:26)
at Object.azj (main.dart.js:9567:5)
at main.dart.js:52630:5
at b9l.a (main.dart.js:4385:62)
at b9l.$2 (main.dart.js:41220:14)
at b7X.$2 (main.dart.js:41217:16)
at b3Q.avX (main.dart.js:42227:36)
at b3Q.a_b (main.dart.js:42229:24)
at jT.h6 (main.dart.js:41487:18)
at b_U.$0 (main.dart.js:41631:37)
```

### Expected Behavior

Google login should work as usual , logging in to firebase and heading the welcome page.

### Steps to Reproduce

1.) launch my project in run mode (the link to my project / project name , Henry form support team has)
2.) click on google login button 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glvHl24VIsbRJ1aruY+9amiIvQ34gbYc0sd4bGA0dCJzuPLMQdvWkN1RCTcPjSnNtekSmml0dpq3Tv/HXDfBcHwuCQLpjyc1IFg3iZD+gQZOBBYezdX96O+dMJ0iC0p+nsBNDCM1oLy0M2nGMGN+Acz7UQe/GIndISq/LZO4=

### Context

just want to launch my project

### Visual documentation

nothing to visualize

### Environment

```markdown
- FlutterFlow version: latest
- Platform: run mode
- Browser name and version: latest chrome on mac
- Operating system and version affected:  mac
```

**Comment by sbis04** [comment]
Hi @frank-bee, thanks for reporting the issue! Have you added `app.flutterflow.io` as the [authorized domain](https://docs.flutterflow.io/data-and-backend/firebase/authentication/google-sign-in#6.-preparing-to-test-the-app) in the Firebase console?

**Comment by sbis04** [comment]
Hey @frank-bee, thanks for reporting the issue! It should be fixed in the next update! 😊

**Comment by frank-bee** [comment]
main.dart.js:33131 Uncaught TypeError: J.cb(...).ac is not a function
    at Object.fg (main.dart.js:33131:24)
    at Object.eT (main.dart.js:5026:3)
    at b25.$1 (main.dart.js:49861:19)
    at c37 (main.dart.js:3139:17)
    at main.dart.js:3147:51

**Comment by azrullahk** [comment]
same here,

**Comment by aemelyanovff** [comment]
Reopening the issue as it is still occurring. New bug report code: IT4Ki8rqx5VgrulA0LrfbflvoCkvJkAnaucoltVDZAE3fJjzG7l/TMnOVBJuOLC0TwhmP1n8uGcxp/vemvzEVsJfYA2BRos//rlQYDvhfFqiMarXEKWWSW5/DedRfVyG0p6k3SJSCM9sWnwH7VyyCNmiQg3tQI+wITIFO8+hB5KK2SrDX1iXc2URm05KZDPz

**Comment by sbis04** [comment]
This should be fixed in the next update!

**Comment by schroederssoftwaresolutionsllc** [comment]
Thanks @sbis04  - any timeline on that update?

**Comment by abuzzahra** [comment]
no update?

**Comment by schroederssoftwaresolutionsllc** [comment]
> no update?

I think this is working now.... it may have been a temporary issue or they updated and its working now.
