### ISSUE TITLE
pincode setFormState doesn't work.

### ISSUE THREAD

**Issue by simon-zhangmuye** [FlutterFlow/flutterflow-issues#1596]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

pincode setFormState doesn't work, set form state works on textfield, but not on pincode widget

### Expected Behavior

edit widget state

### Steps to Reproduce

1.create a new page
2.drop pincode widget 
3.drop a button
4.set button action set form state, select pincode, give it a value
5.run test model.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

pincode controller is not defined

### Context

I cannot edit pincode widget state

### Visual documentation

null

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi, I can reproduce it. 
Dev note - Here is the issue in downloaded code. It should be 'pinCodeController' not textController.

<img width="1193" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/a808251f-d606-4c31-aeab-c882b7833010">

**Comment by wenkaifan0720** [comment]
Hi @simon-zhangmuye. This should be fixed in our next update. Thank you for reporting!

**Comment by simon-zhangmuye** [comment]
@hariprasadms @wenkaifan0720 
I can see you update textController0 to pincode. It should be pincodeController0.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10706610/7e8f4b1f-1df8-46dc-8f7d-4684b78bf087)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/10706610/cb300ac3-0c82-43a9-a528-d3fe14637bff)

**Comment by wenkaifan0720** [comment]
The fix hasn't been pushed yet. Please wait for a few days. Thank you for your patience!

**Comment by simon-zhangmuye** [comment]
@wenkaifan0720 Sorry, you misunderstood what I meant. I can see there is an update in FF from textController0 to pincodeController0. but in the model, you only define a TextEditingController pincode. So the bug still exists.
