### ISSUE TITLE
Route Handling Breaking Dyanmic Link on Cold Start

### ISSUE THREAD

**Issue by nick-chargely** [FlutterFlow/flutterflow-issues#1697]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On a cold start for iOS (and sometimes Android) it loads the deeplink route info in addition to other information using the following format:
/link?deep_link_id={{DEEPLINK_DESTINATION_URL}}&match_type=unique&utm_medium=dynamic_link&request_ip_version=IP_V4&utm_source=firebase

Because of this /link? is not resolved which then shows the route error screen configured in GoRouter in nav.dart. However, the postCallback added does not have a proper check on line 859. 

This line:
`if (widget.state.location.startsWith('/link?request_ip_version')) {`
I believe should be:
`if (widget.state.location.contains('request_ip_version')){`

However, you also need to make sure that you are not navigate to root if the deeplink is already handled

There's a lot going on here behind the scenes. Seems to be a race condition on both Android and iOS between the code and GoRouter. Somewhere the deep_link_id from the broken /link is being identified however it is failing to resolved to the the above issue. Since /link is a bad route (or im assuming every other scenario where error route is displayed) GoRouter fails to push or add any other screens to the stack. Therefore all navigation is broken. 

### Expected Behavior

When a bad route is detected - the current location should still be set to the real route beind dispalyed, not the errored route. It should also allow the user to navigate away when there is a bad route in the stack. 

On cold start iOS should be able to open a deeplink from the app store (using paste board)

### Steps to Reproduce

This was really tough to reproduce since it's mostly a fresh install coming from the app store. However, you can reproduce it through testflight too. When you click on a dynamic link, after it goes to app store do not download, navigate to testflight and install from there. 

The easiest way i found to reproduce was to:

1) Create a dynamic link with format: https://domain.page.link/Whatever
2) Set the destination for the dynamic link to: https://domain.com/link?deep_link_id=https://domain.com/deepRoute&&match_type=unique&utm_medium=dynamic_link&request_ip_version=IP_V4&utm_source=firebase
3) Configure firebase dynamic links in flutter flow 
4) Create a MainPage - `/` route initialization screen (This will also be the page flutterflow uses for error route handling)
5) Create a page with /deepRoute as route
6) Add a button to navigate to another page (push and allow back navigation)
7) Click on the route 
8) You should now see the main page with broken button - cannot navigate away

BONUS:
1. Check out the logcat and you should also be able to spot  GoRouter trying to route to: /deepRoute&&match_type=unique&utm_medium=dynamic_link&request_ip_version=IP_V4&utm_source=firebase

However this is also broken since we are also on a broken page - I believe same reason why step #7 above didnt work is why this is not working

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcr1z4Z2xNtD0a6Jbe9alSQWMjsmULgZl+4acCs8GZT0B4kcYs+kfklUOcO8TwlmI2GZ8XsX/MrRjt/UV+0oHwmcbIRN/5ZyZA7yYGKXV8mtDoS3b0ZQBd1hI3KH4LeFmyJ5BMViLloS72CIHe+/d3bZGZu2NTJEMeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

See the bug report code - this will point to a noRouteHandler page with route /link to bypass FlutterFlow code and resolve the link. I am still testing this but it should give you some idea of the work around needed because of this issue. Also the primary custom action for erroneous link handling. In this custom action we are checking if the route is handled and bail rather than reroute, else reroute to the the path. It's dirty but it's working. 

### Visual documentation

<img width="624" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/d200229b-d258-4a37-b2fc-602d0d3161c5">
<img width="633" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/b21d37e3-7dad-4784-ad65-08a567536ce5">

### Additional Info

The dynamic link handling has cause a lot of annoyances and need for custom handling which is not ideal. Not related to this but you may also want to look into dynamic_link_handler on line 80... This is getting called twice and causing the same page to load on stack. Another area I needed to add a check if the location is already being displayed
<img width="604" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/8db1c320-eac4-4c8b-bd2f-87eb8b02da65">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iOS and Android - primary iOS on cold start issue
- Browser name and version: native
- Operating system and version affected:
```

**Comment by SEGVeenstra** [comment]
I think I have a similar issue.

We are using an email link (dynamic link) to login the user.
The link opens the app just fine and the onPageLoad action authenticates the user.

When the user is authenticated, the app opens the `AgendaPage`. But on this page, all the navigation is broken.
What ever you press, nothing happens, even though the router is receiving the navigation action and thinks it's navigating:
```bash
[GoRouter] pushing /meetingDetailsPage?meetingReference=315_kZnPn39au2cKUGaullrprzY15U52
[GoRouter] getting location for name: "MeetingDetailsPage", queryParameters: {meetingReference: 316_kZnPn39au2cKUGaullrprzY15U52}
[GoRouter] pushing /meetingDetailsPage?meetingReference=316_kZnPn39au2cKUGaullrprzY15U52
[GoRouter] getting location for name: "MeetingDetailsPage", queryParameters: {meetingReference: 316_kZnPn39au2cKUGaullrprzY15U52}
```

When the user restarts the app, and thus is already authenticated, it works as expected.

https://github.com/FlutterFlow/flutterflow-issues/assets/5990148/1ce4a93b-b55e-439a-b012-b20196d1a0c6

**Comment by bscheurman** [comment]
This is exactly what is happening to us, as @SEGVeenstra said.
It only happens on our iOS Release builds, not in debug, and it only happens if Dynamic Links is enabled in FlutterFlow settings.
The app acts almost completely frozen on the first run after install, because all the 'Navigate To's are broken. Then after you kill and restart the app it works fine.
It doesnt even matter whether the app was launched from a dynamic link or not. If Dynamic Linking was enabled when it was built, the app is broken on the very first run.

**Comment by JustUserHere** [comment]
Same issue with my app - on very first run it is frozen. Looking forward for bug fix.

**Comment by agreaves** [comment]
Thank you so much @nick-chargely for the extremely detailed and thorough bug report! We're in the process of fixing this 😊

**Comment by maxIrvine** [comment]
I also have the same issue in my app! Thank you for figuring out the root cause!!!

**Comment by takashiff** [comment]
Thank you for the detailed bug report @nick-chargely. The issue has been resolved and will be reflected in our next deploy.

**Comment by bscheurman** [comment]
Hold on..  I dont think this fixes the issue everyone is having with Navigation being broken after a fresh install on iOS, it still only works after killing and restarting the app.
I updated FlutterFlow v4.0 Released November 17, and built a new iOS build for TestFlight, with Dynamic Links enabled. The items are not clickable.
Anyone else still seeing this problem?

**Comment by DenisDyakonov** [comment]
in my case It begins work after a fresh start on iOS. I updated FF v4.0 Released 18.11.23, built a new iOS build for TestFlight with DL and the same result, The items are not clickable.

**Comment by bscheurman** [comment]
Do these guys understand what a HUGE problem this is?
Just by having dynamic links are enabled, the iPhone app is UNUSABLE until you KILL the app and restart it!
It will get rejected from the store
FIX it for real please
see #1784

**Comment by takashiff** [comment]
Hello, we typically deploy updates to FlutterFlow every other Thursday, so it may take some time for the changes to be reflected on the live version. If this issue persists after the next update, please feel free to follow up on this thread, or with a new bug report. Thank you for your continued patience.

**Comment by DenisDyakonov** [comment]
Hello, I just updated again. This is second deploy from your message that the bug was fixed. The problem is the same place. Do you suggest to wait the Thursday 23.11 for new deploy?

**Comment by takashiff** [comment]
Hello, I've taken another look into the issue and it looks like the fix is not yet live. Thank you again for your continued patience.

**Comment by DenisDyakonov** [comment]
I really need this deploy, hope it will be soon.

**Comment by DenisDyakonov** [comment]
> Hello, I've taken another look into the issue and it looks like the fix is not yet live. Thank you again for your continued patience.

Hi, do you have information about when it can be deployed?

**Comment by SEGVeenstra** [comment]
For me this still is broken.
After logging in with an email link, the apps navigation is broken.

**Comment by Spixz** [comment]
After a fresh install from a dynamic link, the route path has a strange format on iOS. It looks like this:
`/link?deep_link_id=https://XXXXX.page.link/produit?productRef=0Rtjph9ilaSWLumG4Ekn&affiliatedLinkRef=dE6OGb2RHpua1181a22f&match_type=unique&utm_medium=dynamic_link&request_ip_version=IP_V6&utm_source=firebase&match_message=Link+is+uniquely+matched+for+this+device`

Compared to the normal expected route:
`/produit?productRef=0Rtjph9ilaSWLumG4Ekn&affiliatedLinkRef=dE6OGb2RHpua1181a22f`

My solution was to create a new route (**/lib/flutter_flow/nav/nav.dart**) to handle this format, extract the necessary parameters (productRef and affiliatedLinkRef), and pass them to my widget:
```dart
FFRoute(
  name: 'ProduitAfteriOSInstall',
  path: '/link',
  builder: (context, params) {
    Match? matchProduct =
        RegExp(r'productRef=([^&]*)').firstMatch(params.state.location);
    Match? matchLink = RegExp(r'affiliatedLinkRef=([^&]*)')
        .firstMatch(params.state.location);

    if (matchProduct != null && matchLink != null) {
      String productRef = matchProduct.group(1)!;
      String affiliatedLinkRef = matchLink.group(1)!;
      return ProduitWidget(
        productRef: deserializeParam(productRef, ParamType.DocumentReference, false, collectionNamePath: ['Produits']),
        affiliatedLinkRef: deserializeParam(affiliatedLinkRef, ParamType.DocumentReference, false, collectionNamePath: ['Produits']),
      );
    }
    return const WelcomeWidget();
  },
)
```

I hope it's helps you.

**Comment by bscheurman** [comment]
@takashiff  you fixed it so the button navigation works, but the dynamic link still doesnt work properly on iOS on a fresh install. 

The app gets installed but there is no data passed in from the link.
