### ISSUE TITLE
Youtube Player widget repeatedly crashes on Android

### ISSUE THREAD

**Issue by metaflowdev** [FlutterFlow/flutterflow-issues#1920]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

For many of our users the Youtube Player widget crashes when they try to watch a video. We can see in the Crashlytics statistics that this is by far the biggest issue with our app and I we don't see how we could be causing this ourselves.

<img width="1106" alt="Screenshot 2023-11-29 at 2 06 55 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/129390725/ad654661-dc23-41e7-9bf1-5343a44dff6a">

### Expected Behavior

The Youtube Player should not crash.

### Steps to Reproduce

1. Add the Youtube Player widget to the project.
2. Try using the Youtube Player on Android multiple times until the error appears.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki/Hq25dgoddD1s7bbcBvlSc4C0d8TL0nuO0ad0gdGJDyC5k+Z8jBUFtUOLDgT3w3MU6jnnoX/MrluM7hMcADH0uuRr5x1pBUVwHJcHmXVc2gCoS3b3Z8IJpmfGHC4aWr3RN5ObBvcnNl3F+Ie+eXdA7XQ5DFOWwzH+aoXdeK2SrDX1iXc2URm05KZDPz

### Context

It effects many of our Android App users. This is the biggest issue we have within our app by far. We are receiving bad reviews and users are frustrated.

### Visual documentation

N/A

### Additional Info

Here is a stacktrace and a log from crashlytics, I am happy to share more data if it helps solve the issue.

Log: https://zerobin.org/?8cb528498dbb6c7e#FAusePHeAAcqL8a6GwVyouytLbET3qfmayDynwNyPSvt

Stacktrace: https://zerobin.org/?feda1b7eb0aa6690#8Wpo6wZvyf5QnihFWk4ZdR637oTuT75jDzkfdjKA5Ceo

I also reported this isse here but nobody reacted for 10 days: https://community.flutterflow.io/c/bugs/post/native-youtube-widget-crashes-app-crashlytics-report-eugGKCzUTzxXSTX

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Android
- Browser name and version: ?
- Operating system and version affected: 11, 12, 13, 14
```

**Comment by wenkaifan0720** [comment]
Hi @metaflowdev. We have identified the issue and is working on it.

**Comment by metaflowdev** [comment]
> Hi @metaflowdev. We have identified the issue and is working on it.

Thank you! Any idea when we can expect the fix to be implemented?

**Comment by metaflowdev** [comment]
> Hi @metaflowdev. We have identified the issue and is working on it.

Hi @wenkaifan0720 , do you have an ETA for the fix?

**Comment by fjahr** [comment]
Hello, with every new version we release, we get warnings from crashlytics that our release is unstable because of this issue. Can we please get an estimate when this will be solved? Thank you!

<img width="439" alt="Screenshot 2023-12-20 at 12 00 49 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/1322187/5450176c-e679-4451-8fc5-2e54fbd12810">

@wenkaifan0720 @katherineqian @SameerShahzad99 @asmengistu

**Comment by metaflowdev** [comment]
Hello, with every new version we release, we get warnings from crashlytics that our release is unstable because of this issue. Can we please get an estimate when this will be solved? Thank you!

<img width="439" alt="Screenshot 2023-12-20 at 12 00 49 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/129390725/97458a2b-5352-4b0c-a4b7-f8914242ecd7">

@wenkaifan0720 @katherineqian @SameerShahzad99 @asmengistu

**Comment by wenkaifan0720** [comment]
Hi @metaflowdev. This should be fixed in our next update. Thank you for your patience.

**Comment by metaflowdev** [comment]
@wenkaifan0720 Thanks! Can you confirm that this is included in the FlutterFlow version that I can see online right now and not a future version? This one: `FlutterFlow v4.0 released December 22, 2023`. Thanks again!

**Comment by wenkaifan0720** [comment]
Unfortunately not yet. Besides, since it's the holidays, our next release might be delayed a bit.

**Comment by metaflowdev** [comment]
@wenkaifan0720 Then I don't understand why this is closed if the fix is not available yet. So it will definitely be in the next release from now whenever it will be released? Can you notify me here when the fix is released?

**Comment by metaflowdev** [comment]
@wenkaifan0720 I the fix now included in this release?

```
FlutterFlow v4.0 released January 4, 2024
Flutter version is 3.13.7
```

**Comment by metaflowdev** [comment]
Hello? Can someone answer me if this is fixed now? I don't want to do a release if it's pointless... Thanks!

@wenkaifan0720 @katherineqian @SameerShahzad99 @asmengistu

**Comment by metaflowdev** [comment]
Hello, we did a deployment last week with this version:

```
FlutterFlow v4.0 released January 15, 2024
Flutter version is 3.13.7
```

However the issue still persists. I think that's the 3rd version of FlutterFlow that has been release since this issue has been closed. Why is the fix not included and when will it be included?

@wenkaifan0720 @katherineqian @SameerShahzad99 @asmengistu

**Comment by wenkaifan0720** [comment]
Hi @metaflowdev. I am very sorry for the delayed response. just checked that our latest prod (released on Jan 20th) is generating code that contains the fix. 

To give you more context, the proposed fix to the issue you saw has not been merged into the main branch of the package for over a year (https://github.com/sarbagyastha/youtube_player_flutter/pull/730). We had to create our own fork and point FF projects to that fork which contains the fix. 

Please let me know if the latest version solves your issue. I will reopen this issue until your issue is resolved. Thank you for your patience.

**Comment by metaflowdev** [comment]
@wenkaifan0720 Thank you for the heads-up and the details! When I refresh I am currently still seeing the release from Jan 15th but when the release from the 20th becomes available I will release a new version instantly and give feedback afterwards. Thanks again!

**Comment by fjahr** [comment]
@wenkaifan0720 Hm, the version from the 20th never became available to me but now I see this one. I suppose this one also includes the fix, right?

```
FlutterFlow v4.1 released January 25, 2024
Flutter version is 3.13.7
```

**Comment by metaflowdev** [comment]
@wenkaifan0720 Hm, the version from the 20th never became available to me but now I see this one. I suppose this one also includes the fix, right?

```
FlutterFlow v4.1 released January 25, 2024
Flutter version is 3.13.7
```

**Comment by wenkaifan0720** [comment]
Yes. And let me know if the fix works for you.

**Comment by metaflowdev** [comment]
@wenkaifan0720 unfortunately the fix hasn't worked. This latest release (0.3.14) that came out yesterday already saw several crashes with the same error message.

<img width="828" alt="Screenshot 2024-01-30 at 6 01 52 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/129390725/9482393d-ce0f-4705-8d27-e3e7f440b13d">

**Comment by metaflowdev** [comment]
> This issue is stale because it has been open for 7 days with no activity. If there are no further updates, a team member will close the issue.

This issue is still unresolved

**Comment by wenkaifan0720** [comment]
Hi @metaflowdev. Sorry for the late reply, I was out of office for a while. I made this test project: https://app.flutterflow.io/project/youtubeplayer-myqad8 and tested on my Samsung S23 (on Android 14) for quite some time but haven't experienced any crash or see this error message. 

I do, however, think the crashes your users are experiencing are very real. I found another place in the youtube_player package that has the same issue that we fixed recently, and had just fixed it. Please bear in mind that this package is developed by someone else, so finding issues in it is challenging. And the error message by firebase crashlytics that you provided helped a lot. Could you try to do another release (or do a local test on a real device) and see if the issue goes away?

**Comment by metaflowdev** [comment]
@wenkaifan0720 We still see the issue with the latest release.
