### ISSUE TITLE
Default App State value not applied when "Secure persisted fields" is enabled

### ISSUE THREAD

**Issue by vitoras** [FlutterFlow/flutterflow-issues#2257]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to set the default value for a bool App State variable to true, it works fine if "Secure persisted fields" option is not enabled. Otherwise, it defaults to false.

### Expected Behavior

Default App State value should remain regardless of whether "Secure persisted fields" option is enabled or not.

### Steps to Reproduce

1. Create App State with boolean type, give it any name (e.g. "testVariable"), and set as persisted;
2. Set its default value to true and enable "Secure persisted fields" option;
3. Add text widget and set its value with a if condition, where if testVariable then "variable is true" else "variable is false";
4. Start test mode;
5. It will show text as "variable is false";
6. End test mode;
7. Go back to App State screen and disable "Secure persisted fields" option;
8. Start test mode again;
9. Now the text is shown as "variable is true".

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gos9f+6XXKMJAhR4jNlx7bZNF08JTZxE0GK71O4wpWsz8QGhoOrSYdG9IP1f+kmQ0wMGKiIXyGvEVAAyHY4A71pdpED3LUk+ibpCtEpOCOnFBI+VXfHKe0J6rhh0lJbNedV1pig/GSw==

### Context

It's affecting workflow logic in my app when it needs to check default App State variable before changing it.

### Visual documentation

1. Create App State with boolean type, give it any name (e.g. "testVariable"), and set as persisted;

![Captura de Tela 2024-01-27 às 20 39 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/52968863-1bcd-4b43-844d-9ee1e03752d2/889883b9-5188-49b7-af7c-2d233899db34?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81Mjk2ODg2My0xYmNkLTRiNDMtODQ0ZC05ZWUxZTAzNzUyZDIvODg5ODgzYjktNTE4OC00OWI3LWFmN2MtMmQyMzM4OTlkYjM0IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.Nh-hRNjO4deXcDjrFviwJqjYeKUNy1nZY8H36mntqvQ)

1. Set its default value to true and enable "Secure persisted fields" option;

![Captura de Tela 2024-01-27 às 20 40 24](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f062e858-bb64-43e8-8c60-e1df6dcd1e1f/19d44db9-f624-44ab-928f-224463d7d280?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMDYyZTg1OC1iYjY0LTQzZTgtOGM2MC1lMWRmNmRjZDFlMWYvMTlkNDRkYjktZjYyNC00NGFiLTkyOGYtMjI0NDYzZDdkMjgwIiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.\_G9NEcKzmEfqKdMT_j7litJDpm_pFeRdysEE2iiel7A)

1. Add text widget and set its value with a if condition, where if testVariable then "variable is true" else "variable is false";

![Captura de Tela 2024-01-27 às 20 41 33](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/426f2da7-131a-4e41-a551-8610b44cc686/1c0d9a7f-0959-443c-86a8-f92e437ce4c9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MjZmMmRhNy0xMzFhLTRlNDEtYTU1MS04NjEwYjQ0Y2M2ODYvMWMwZDlhN2YtMDk1OS00NDNjLTg2YTgtZjkyZTQzN2NlNGM5IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.wGI9p4Erohtm8bFnJzmOLt4fJ-UbV-wqQ485jS1GxlQ)

1. Start test mode;

![Captura de Tela 2024-01-27 às 20 42 23](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bac9b6a2-0618-4cf2-b3aa-543fae5bbfe3/9b849b7c-70fc-44c3-bf7b-7a1067bd75a4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iYWM5YjZhMi0wNjE4LTRjZjItYjNhYS01NDNmYWU1YmJmZTMvOWI4NDliN2MtNzBmYy00NGMzLWJmN2ItN2ExMDY3YmQ3NWE0IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.lUdFvHl_elt3Oe9580rYwOUlRPTVMePumV469c5z6HM)

1. It will show text as "variable is false";

![Captura de Tela 2024-01-27 às 20 43 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6313406c-eb5a-4abc-a2b3-6bfb2887f9c1/ed20b533-9bd8-4114-bcf6-be219ef8b584?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MzEzNDA2Yy1lYjVhLTRhYmMtYTJiMy02YmZiMjg4N2Y5YzEvZWQyMGI1MzMtOWJkOC00MTE0LWJjZjYtYmUyMTllZjhiNTg0IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.NoZ1EPmCRW6ozOP0aFsTsyrDrT6OVqbFqWBf5zfSP8g)

1. End test mode;

![Captura de Tela 2024-01-27 às 20 43 45](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c50d25e8-ec20-425c-b07e-58926ac9d75a/3fb7d8b5-f546-457a-b860-acce256bdfe1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNTBkMjVlOC1lYzIwLTQyNWMtYjA3ZS01ODkyNmFjOWQ3NWEvM2ZiN2Q4YjUtZjU0Ni00NTdhLWI4NjAtYWNjZTI1NmJkZmUxIiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.WS1mAh8wAn-i5A1e5t5Hd9o24ppTLkpom8v4p-FCPnU)

1. Go back to App State screen and disable "Secure persisted fields" option;

![Captura de Tela 2024-01-27 às 20 44 08](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d994b142-b16d-4fac-b7ac-7282c8916b4b/dd806f6e-b913-4d3d-a1b5-1750d24009a8?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kOTk0YjE0Mi1iMTZkLTRmYWMtYjdhYy03MjgyYzg5MTZiNGIvZGQ4MDZmNmUtYjkxMy00ZDNkLWExYjUtMTc1MGQyNDAwOWE4IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.ybRfFiEwJWTiCLIo38NjKIMJuft5eqphWQ_tKyC0WXs)

1. Start test mode again;

![Captura de Tela 2024-01-27 às 20 44 29](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/984ad239-7b6d-46f4-be28-a426f1a9fa98/7c4c042c-6c8c-41bd-94b9-d5307235c117?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ODRhZDIzOS03YjZkLTQ2ZjQtYmUyOC1hNDI2ZjFhOWZhOTgvN2M0YzA0MmMtNmM4Yy00MWJkLTk0YjktZDUzMDcyMzVjMTE3IiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.-LEjv-uhf-9IIVxpZ4i1TXcCpARAhvveT2eRnxlHhZg)

1. Now the text is shown as "variable is true".

![Captura de Tela 2024-01-27 às 20 45 22](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/3b8315e5-fbc7-4150-82d0-a348c368bec8/50316fb6-3ca4-4a5a-9d06-1942f1562dc2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zYjgzMTVlNS1mYmM3LTQxNTAtODJkMC1hMzQ4YzM2OGJlYzgvNTAzMTZmYjYtM2NhNC00YTVhLTlkMDYtMTk0MmYxNTYyZGMyIiwiaWF0IjoxNzA3MTQxMzM4LCJleHAiOjMzMjc3NzAxMzM4fQ.JIFdfkC1i9UhicEJ1W3ETuT-F1lgtZ7iX6WXH76ZfDM)

### Additional Info

Just for the record, this exact same behavior happens both on test mode and run mode.

### Environment

```
- FlutterFlow version: 4.1.23
- Platform: MacOS Desktop
- Browser name and version: Brave v1.62.153
- Operating system and version affected: macOS Sonoma 14.2.1
```

**Comment by hariprasadms** [comment]
Hi @vitoras - Thanks for submitting the issue. I can reproduce the above steps.

**Comment by leighajarett** [comment]
I believe this is now fixed, thanks for flagging!

**Comment by fafa16** [comment]
Hello, we agree that the issue is still here right??

**Comment by semaforceOne** [comment]
This is still a issue, Boolean Persistent does not store default, if you remove persistent it works fine.

**Comment by AvinashGandhasiri** [comment]
This is still an issue. The app states that saving defaults is not possible when in persisted mode.

**Comment by junyi893** [comment]
Still an issue. Like one year later? Really?
