### ISSUE TITLE
Audio recording codec issue.

### ISSUE THREAD

**Issue by DedeStPete** [FlutterFlow/flutterflow-issues#2332]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Audio recordings made by iPhones are not playable by iPhones, if local path file is to play. If streamed from Firebase, it plays. If recording is made by Android, these recordings are not playable by iPhones, streamed.

### Expected Behavior

Recordings made on both platforms should be played back on both platforms with no problems.

### Steps to Reproduce

1. Make microphone audio recording on android. 2. Upload to Firebase. 3 Play recording in iPhone.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oz8r6w5N2rsNA0bXqdflV+CQXQkg5argvicpOWSsbfL74E+0iOfSkP1FpUtCzaHx6KFeGhkQy0Nrxk+HpUvU6GzmeRYRd/rhuVxPPbFmmMLamC5OOekR9P8JYJn6O36WJviRRCOhacVIZ22apfOuATT2Cf9qOYwx5e6fDbOY=

### Context

Making audio messages section in the app.

### Visual documentation

![1](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/14fd6e56-28f8-4aab-915b-0e0c5b9a613d/9205ca95-0a3a-4e7d-9935-f2a23588ae9b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xNGZkNmU1Ni0yOGY4LTRhYWItOTE1Yi0wZTBjNWI5YTYxM2QvOTIwNWNhOTUtMGEzYS00ZTdkLTk5MzUtZjJhMjM1ODhhZTliIiwiaWF0IjoxNzA3Njc5ODEwLCJleHAiOjMzMjc4MjM5ODEwfQ.FxVyTPRe7MiY_KnXhzk9m7FQJoI_2AzR-evyxVVFy3k)

![2](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/430597a1-ccd3-4ce8-93ca-fe296bd35a8a/47c524b8-4974-49b2-825c-1b36f3eca8af?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MzA1OTdhMS1jY2QzLTRjZTgtOTNjYS1mZTI5NmJkMzVhOGEvNDdjNTI0YjgtNDk3NC00OWIyLTgyNWMtMWIzNmYzZWNhOGFmIiwiaWF0IjoxNzA3Njc5ODEwLCJleHAiOjMzMjc4MjM5ODEwfQ.4ovK8woguLUJrN2IC8_HjClN5ZoWdzFCLM8RAieztao)

### Additional Info

Since initial codec is aac m4a, naming file .mp3 is wrong. Files to upload have to have .m4a extension.

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: Web
- Browser name and version: Chrome Version 121.0.6167.160 (Official Build) (arm64)
- Operating system and version affected: Mac OS Sonoma 14.3
```

**Comment by DedeStPete** [comment]
In summary: iOS doesn't recognize recorded as .mp3 thus cannot playback it. It can record though, and recorded can be played on Android. Anyway, to achieve result, recordedFileBytes.mp3 should be renamed to recordedFileBytes.m4a

**Comment by allik007** [comment]
Same problem

**Comment by jimff** [comment]
Me too.  iOS mp3 files are not recognised by whisper.

**Comment by sbis04** [comment]
This should be fixed in the next update!

**Comment by allik007** [comment]
> This should be fixed in the next update!

Omg, awesome! @sbis04  could you specify the date pls? 
Thanks!

**Comment by jimff** [comment]
Audio recording in Flutterflow seems broken since today.  Yesterday my app was working fine, after recording audio I was able to just upload it to supabase where it was stored in a bucket and I could play the file just fine.  Now it seems to do everything fine, only it stores 0 second recordings in Supabase.  Very frustrating.

**Comment by DedeStPete** [comment]
Issue is NOT fixed. Still, iPhone cannot play files recorded on Android, while Android can play files recorded on any platform. Why naming files .mp3, when they are recorded as .m4a initially?

**Comment by allik007** [comment]
Flutter flow team just don't care about their users
