### ISSUE TITLE
Update SDK version issue (Using Old iOS 16.2 SDK vs New 17.0)

### ISSUE THREAD

**Issue by pstatile** [FlutterFlow/flutterflow-issues#2334]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When publishing to Apple Store, they send a warning message about old SDK used.

### Expected Behavior

Publish and get no worning message about SDK

### Steps to Reproduce

Publish an app to the app store.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/6w5N2rt9G+KniaO5aqGQ7GUMfWOdEket+EA0hfZDtBLATdczCbVVLYtfmS31DPmH+sEkfwvDpkd/1F+04YU+BUaZTzL5XQQ3jVlGhRcmpELqeW3ZBBeFmJ0yi0cHYnRFCNbBidEYk2mGuffCdG3qCf9qOYwx5e6fDbOY=

### Context

It does not block the app publication, but there is a date limit to correct it.

### Visual documentation

Email received:

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\`Dear Developer,

We identified one or more issues with a recent delivery for your app version 1.0.34 (89). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\`

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: iOS
- Browser name and version: -
- Operating system and version affected: -
```

**Comment by takashiff** [comment]
Hi @pstatile, thank you for the bug report. We currently have plans to update the SDK in the near future before the deadline of April 29, 2024. Unfortunately, I cannot provide an ETA on when the update will be rolled out, but you should be able to safely ignore this warning. Thanks

**Comment by Wittrup90** [comment]
Same problem.

**Comment by MortadhaFadhlaoui** [comment]
same issue

**Comment by SCMG7** [comment]
I have the same issue, even tho I have updated to the latest version of xcode and flutter, when I execute 'xcodebuild -showsdks' to see my sdk, its says iOS SDKs: iOS 17.2, and we keep getting that email from Apple, what is the issue here?

**Comment by MrRongoose** [comment]
> I have the same issue, even tho I have updated to the latest version of xcode and flutter, when I execute 'xcodebuild -showsdks' to see my sdk, its says iOS SDKs: iOS 17.2, and we keep getting that email from Apple, what is the issue here?

Being updated soon per post above. It's on Flutterflow's side, don't think we can do anything from the no-code side to correct. https://github.com/FlutterFlow/flutterflow-issues/issues/2334#issuecomment-1944963321

**Comment by takashiff** [comment]
Hi everyone, we are still currently addressing this issue and have plans to have this resolved in the near future. Thank you for your patience.

**Comment by AyanamiDaisuki** [comment]
Same issue. Will Apple approve the app review even with the existence of this issue?

**Comment by MrRongoose** [comment]
> Same issue. Will Apple approve the app review even with the existence of this issue?

Yes. Just gives a warning for now but my builds are getting approved

**Comment by epszteyn** [comment]
It's now April 25, 4 days before the deadline, and I'm still seeing this issue. Is there a new release that fixes it?

**Comment by Andrey5045** [comment]
18.05.2024, not done :-( I cannot compile my projects for iOS on GitHub anymore...

**Comment by Phillewis63** [comment]
Is there an update on this issue?

**Comment by pstatile** [comment]
HI! Got again a message from Apple:




Hello,

We noticed one or more issues with a recent delivery for the following app:

   - XXXX
   - Version XXXX
   - Build XXXX

Although delivery was successful, you may want to correct the following
issues in your next delivery. Once you've corrected the issues, upload a
new binary to App Store Connect.

*ITMS-90725: SDK version issue* - This app was built with the iOS 17.4 SDK.
Starting April 24, 2025, all iOS and iPadOS apps must be built with the iOS
18 SDK or later, included in Xcode 16 or later, in order to be uploaded to
App Store Connect or submitted for distribution.

Apple Developer Relations

**Comment by jesus-like-a-startup** [comment]
Hello, any progress? 
I have the same issue

<img width="688" alt="Image" src="https://github.com/user-attachments/assets/b5293e8c-c7a4-444e-bb3c-e2548bf46533" />
