### ISSUE TITLE
Windows FlutterFlow Desktop App crashes on startup

### ISSUE THREAD

**Issue by DimZakir1** [FlutterFlow/flutterflow-issues#2584]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After downloading and installing the application for Windows, the login page opened.
I logged into the system using my username and password, after which the project selection page opened.
I clicked on one of the projects and the Windows application crashed immediately.

Opening the application again, it starts checking for updates, now it immediately crashes. A message about permission to check for updates automatically is visible for a split second.

When deleting and reinstalling the same thing happens, the application immediately crashes

### Expected Behavior

Launching an application for Windows and working in it

## Installation for the first time (Previously, there was no FlutterFlow for Windows application on the PC)

1. Download and install the application
2. Open the application and log in to your account with username and password
3. Selecting the current project
4. The application crashes

## When reopening or reinstalling

1. Opening the application
2. Checking for updates, you can also see a window with permission for automatic updating, which cannot be clicked on
3. Crashes after a couple of seconds

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

Can't open to the FlutterFlow Desktop App

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/140861648/510265f9-f72d-47ff-85ca-8ebe55a5b16d](https://github.com/FlutterFlow/flutterflow-issues/assets/140861648/510265f9-f72d-47ff-85ca-8ebe55a5b16d)

### Additional Info

*No response*

### Environment

```markdown
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.4, on Microsoft Windows [Version 10.0.19045.4170], locale ru-KZ)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.8.2)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.85.1)
[√] Connected device (3 available)
[√] Network resources
 
• No issues found!
```

**Comment by darosaweb** [comment]
I have the same behaviour.

**Comment by verdavaine** [comment]
Me too maybe a problem with Windows10

**Comment by treirouxel88** [comment]
Same here, i have these crashes on the work computer with Windows 11, weird because its running smoothly on my home computer (with Windows 10), seems to be related with Firestore, i made the app working again for few minutes by deleting "flutterflow-io-6f20" located in %localappdata%\firestore\[DEFAULT] until it crashes again

**Comment by DimZakir1** [comment]
> Same here, i have these crashes on the work computer with Windows 11, weird because its running smoothly on my home computer (with Windows 10), seems to be related with Firestore, i made the app working again for few minutes by deleting "flutterflow-io-6f20" located in %localappdata%\firestore[DEFAULT] until it crashes again

Hmm, it seems that it helped, but also until the first reboot.
I didn’t go into my big main project, I went into the test project.
Everything seemed to be working, but as soon as I decided to restart FlutterFlow, it started crashing again

**Comment by omkami** [comment]
> Same here, i have these crashes on the work computer with Windows 11, weird because its running smoothly on my home computer (with Windows 10), seems to be related with Firestore, i made the app working again for few minutes by deleting "flutterflow-io-6f20" located in %localappdata%\firestore[DEFAULT] until it crashes again

Thanks for sharing. It seems the .log file is the main one causing this problem. I wrote a batch script that deletes that file before every launch, and it works seamlessly without me having to log in every time.

**Comment by adamriha97** [comment]
Same here, still the same.. works ok on 2 w10 PCs, not on the third :(

**Comment by italoengdev** [comment]
do not worked here too

**Comment by thekcorp** [comment]
Similar issue here. Mine opens and starts automatically the software update, and then immediately crashes.

**Comment by gstalteri57** [comment]
Same issue: Opens and starts automatically the softwre update and then crashes

**Comment by MasterOTOKKY** [comment]
Same issue: I see the software update and then it crashes.

**Comment by laurencetroyv** [comment]
same issues

**Comment by AhmedWagdi1** [comment]
Same problem here !! and it doesn't look like the team is going to take any action soon !!

**Comment by DimZakir1** [comment]
I discovered this problem here a long time ago, and the application still does not work.  Indeed the flutterflow team just doesn't seem to want to do anything about it

**Comment by dbfcode** [comment]
Same issue!!!

**Comment by salvanin** [comment]
The problem is that we have no position on whether something is being done

**Comment by aemelyanovff** [comment]
Sorry for the late response.

We are currently unable to reproduce the issue, so we need everyone's help. If you are experiencing this issue, please:
- Go to https://app.flutterflow.io and open the last project that you opened in the Windows app before it started crashing.
- [Create a bug report code](https://docs.flutterflow.io/widgets-and-components/widgets#get-bug-report-code) from anywhere in the project.
- Reply here with the bug report code.

**Comment by DimZakir1** [comment]
The application worked for me!

I opened this topic a long time ago and I don’t know if the FF team did anything with the Windows application.

If it helps, here's what changed for me when the application started working:

I changed the computer components:
1. Changed the rtx 3060 video card,
2. Changed the processor to i7 7700,
3. Changed the motherboard to strix b250f gaming
4. Windows did not reinstall

Old components:
1. Gtx 1060, 2. i7 960, 3. asus p6t deluxe v2

After this, the FF application started working for some reason

If you need additional information please contact

**Comment by leoviveiros** [comment]
> Sorry for the late response.
> 
> We are currently unable to reproduce the issue, so we need everyone's help. If you are experiencing this issue, please:
> 
> * Go to https://app.flutterflow.io and open the last project that you opened in the Windows app before it started crashing.
> * [Create a bug report code](https://docs.flutterflow.io/widgets-and-components/widgets#get-bug-report-code) from anywhere in the project.
> * Reply here with the bug report code.

IT40ksjf35VIsbRJ+Kr+csFVoCU5Jlgga7gzm8FBaCosfZT2BLMcec/RVERDTs+oTwlfPlqgjWoW3PSMuN71OvQ6YAmZRoBn+JBIdj3yYEymac3WFJWgTmsmO+FXGBWa0LW3uhB7BMd0SHgT62CMIunISh/qJqLGO3oSDq/LZO4=

**Comment by leighajarett** [comment]
Hi there, thank you all for the information! We have spent a lot of time trying to figure out the root cause of this issue but we cannot reproduce 🙁 <br><br>Unfortunately, I don't think there is anything more we can do for this issue at the moment. I am going to close this issue as Not Planned. But we will continue to keep an eye on reports that come in, and any additional information. If there seems to be some action we can take to resolve this issue, we will reopen it.<br><br>However, it seems that the best we can do is recommend that you try upgrading CPU and video card, since that seems to have worked for some users.<br><br>I know this is very frustrating, I'm sorry for any problems this has caused!

**Comment by AhmedWagdi1** [comment]
let me give you a hint,, for flutter team .. the app works when I delete the folder inside `C:\Users\[myUserName]\AppData\Local\firestore\[DEFAULT]` it works and doesn't crash for a while ..then it suddenly closes after some minutes of normal working .. and never starts again till we delete this folder again .. so it is related to fire-store files.

P.S.: it is not related to hardware, GPU, or CPU because it worked fine before. At some point, this happens after adding Firestore to my app.

**Comment by leighajarett** [comment]
Super helpful, thanks!

**Comment by DimZakir1** [comment]
> Super helpful, thanks!

Hello. I want to say that the application did not work for me at all from the very beginning of installation.
I just couldn't even open the FF app as shown in the video above.
Deleting folders, reinstalling, nothing helped throughout the entire time from the moment I opened this topic.

I don’t know how, but changing the components of my computer helped and the application started. I'm not sure that this will help other people in any way, I just stated the fact that FF started working after this

I also want to say that I have several open projects in FF that I am working on, and everywhere they have a Firebase database connected and a lot of custom code for working with Firebase and Firestore.
But as I said earlier, I couldn’t log into any of them; all this time I had to work on a MacBook, where everything works fine with the FF application.

I hope you will somehow solve this problem over time, so that all other users can also work in the FF desktop application, since FlutterFlow is an amazing tool!

**Comment by leonidesdreveckjr** [comment]
Hello @leighajarett 

Any news here?

Same problem persists: open FF, it crashs after use for a few minutes, I delete folder C:\Users\[myUserName]\AppData\Local\firestore\[DEFAULT], open FF...

**Comment by leonidesdreveckjr** [comment]
> Hello @leighajarett
> 
> Any news here?
> 
> Same problem persists: open FF, it crashs after use for a few minutes, I delete folder C:\Users[myUserName]\AppData\Local\firestore[DEFAULT], open FF...

Not sure, but I think it crashs seconds after I add a new widget to the project

**Comment by leighajarett** [comment]
Oh no, I'm sorry 🙁 We haven't been able to reliably reproduce crashes and figure out the root cause on Windows - so we've set up logging on the macOS side which allows us to pinpoint root causes for mac crashes that can also lead to crashes on Windows. We're going through and fixing these as they come. If you're able to send over your crash logs that can help us better understand what might be going on!

**Comment by AhmedWagdi1** [comment]
both mac and windows crashed on start-up.. and the flutterflow team decided that its better to ignore the issue and close it all !!

**Comment by AhmedWagdi1** [comment]
@leighajarett 
here is the error log from windows event viewer, am sure it may help you some how :

```
Log Name:      Application
Source:        Application Error
Date:          9/13/2024 2:23:03 PM
Event ID:      1005
Task Category: Application Crashing Events
Level:         Error
Keywords:      
User:          AHMED\ahmed
Computer:      ahmed
Description:
Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program flutterflow because of this error.

Program: flutterflow
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 0x0
Disk type: 0x0
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
    <EventID>1005</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000000</Keywords>
    <TimeCreated SystemTime="2024-09-13T11:23:03.6794741Z" />
    <EventRecordID>1381</EventRecordID>
    <Correlation />
    <Execution ProcessID="2828" ThreadID="9064" />
    <Channel>Application</Channel>
    <Computer>ahmed</Computer>
    <Security UserID="S-1-5-21-3034306258-2129343333-2968569947-1001" />
  </System>
  <EventData>
    <Data Name="FilePath">
    </Data>
    <Data Name="AppName">flutterflow</Data>
    <Data Name="StatusCode">0x0</Data>
    <Data Name="MediumType">0x0</Data>
  </EventData>
</Event>
```

**Comment by AhmedWagdi1** [comment]
so still no updates !?!

**Comment by Rivounet** [comment]
have the same issue. solution?

**Comment by leighajarett** [comment]
Thanks for sending those over, we will take a look

**Comment by davidsomnus** [comment]
same here.. just exits immidiately after starting. windows 10.

deleted the folder under [default] as per @AhmedWagdi1, it opens and crashes shortly after. any news, @leighajarett??

thanks!

**Comment by leighajarett** [comment]
We're continuously monitoring crash logs and fix reasons for crashing as we detect them through our monitoring efforts. Even though you experience the same crash experience, it could be due to a huge variety of things so it's hard to say if we have a fix for your specific issue 🙁 <br><br>The best thing you can do is send over any additional information like OS version and crash logs. Thank you so much and sorry that's happening 🙁

**Comment by syg-eliseu** [comment]
I opened a new issue because I hadn't found this report from so many users. In my case the problem occurs on 2 different notebooks with Windows 10 and 11. The error identified in the WIndows Event Viewer has to do with ntdll.dll and KERNELBASE.dll

Issue:
[#5036](https://github.com/FlutterFlow/flutterflow-issues/issues/5036)

**Comment by WarRusher** [comment]
Hello,
For what it's worth I  downloaded the app yesterday and have the same problem. Deleting the "Firestore" folder allows the app to actually start up, but as soon as you go into the project it crashes.   

Is there any movement on this please?

**Comment by sixthtulip** [comment]
Hi. I have the same problem. The app closes 1-2 seconds after launch. I reinstalled it and it doesn't help. In my project I use SQL and Revenue Cat and if I understood correctly in this case I can't test the project in Test Mode or Run Mode (one way or another they don't work either). I don't know how else I can test my application and find the problems that I had after deploying it to Google Play (internal testing). What do you think - is it worth paying for a subscription, recommending FF to friends and continuing to use it?
P.S. If you look in the FF community and type Local Run in the search, you will see about a hundred posts about it not working.

**Comment by tupfe** [comment]
same problem!

**Comment by thiago-copertec** [comment]
Segue os logs de erro.
Gera 3 erro de eventos do Windows.
Anexo dos arquivos

[Report.txt](https://github.com/user-attachments/files/18597228/Report.txt)

 relacionados


**_1 ARQUIVO DE ERRO_**

`Nome do Log:   Application
Fonte:         Windows Error Reporting
Data:          30/01/2025 01:10:59
Identificação do Evento:1001
Categoria da Tarefa:Nenhum
Nível:         Informações
Palavras-chave:Clássico
Usuário:       N/D
Computador:    DESKTOP-5R7GBU8
Descrição:
Falha no bucket 1847949023309546236, tipo 4
Nome do Evento: APPCRASH
Resposta: Não disponível
ID do CAB: 0

Assinatura do problema:
P1: flutterflow.exe
P2: 5.1.2.0
P3: 679a68b4
P4: flutterflow.exe
P5: 5.1.2.0
P6: 679a68b4
P7: c000001d
P8: 00000000007d3967
P9: 
P10: 

Arquivos anexados:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6CB.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD805.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD8A2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD8B2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD8D2.tmp.txt

Esses arquivos talvez estejam disponíveis em:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_flutterflow.exe_feff976d7c6be3ef69a61be2ee9cfb1f90812844_9191b63c_3541d443-dd77-4f5d-9229-575ebd1ec739

Símbolo da análise: 
Verificando novamente se há uma solução: 0
ID do Relatório: 7229179e-4bc0-47c2-9ea9-93b81c6bb3fd
Status do Relatório: 268435456
Bucket com hash: f258008063ae326949a53bd8896542fc
Guid do CAB: 0
XML de Evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2025-01-30T04:10:59.3732593Z" />
    <EventRecordID>3624</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-5R7GBU8</Computer>
    <Security />
  </System>
  <EventData>
    <Data>1847949023309546236</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Não disponível</Data>
    <Data>0</Data>
    <Data>flutterflow.exe</Data>
    <Data>5.1.2.0</Data>
    <Data>679a68b4</Data>
    <Data>flutterflow.exe</Data>
    <Data>5.1.2.0</Data>
    <Data>679a68b4</Data>
    <Data>c000001d</Data>
    <Data>00000000007d3967</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD6CB.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD805.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD8A2.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD8B2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERD8D2.tmp.txt</Data>
    <Data>\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_flutterflow.exe_feff976d7c6be3ef69a61be2ee9cfb1f90812844_9191b63c_3541d443-dd77-4f5d-9229-575ebd1ec739</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>7229179e-4bc0-47c2-9ea9-93b81c6bb3fd</Data>
    <Data>268435456</Data>
    <Data>f258008063ae326949a53bd8896542fc</Data>
    <Data>0</Data>
  </EventData>
</Event>`




**_2 ARQUIVO DE ERRO_**

`Nome do Log:   Application
Fonte:         Application Error
Data:          30/01/2025 01:10:56
Identificação do Evento:1005
Categoria da Tarefa:(100)
Nível:         Erro
Palavras-chave:Clássico
Usuário:       N/D
Computador:    DESKTOP-5R7GBU8
Descrição:
O Windows não pode acessar o arquivo  por um destes motivos:  há um problema de conexão com a rede, o disco no qual o arquivo está armazenado ou nos drivers de armazenamento  instalados neste computador, ou o disco está ausente. O Windows fechou o programa flutterflow por causa desse erro.

Programa: flutterflow
Arquivo: 

O valor do erro está listado na seção Dados Adicionais.
Ação do Usuário
1. Abra o arquivo novamente. Esta situação pode ser um problema temporário corrigida quando o programa é executado novamente.
2. Se o arquivo ainda não puder ser acessado e 
	- não estiver na rede,  o administrador da rede deverá verificar se não há um problema com a rede e se o servidor puder ser contatado.
	- Está em um disco removível, por exemplo, um disquete ou CD-ROM, verifique se o disco está completamente inserido no computador.
3. Verifique e repare o sistema de arquivos ao executar CHKDSK. Para executar CHKDSK, clique em Iniciar, clique em Executar, digite CMD e clique em OK. No prompt de comando, digite CHKDSK /F e pressione ENTER.
4. Se o problema persistir, restaure o arquivo de uma cópia de backup.
5. Determine se outros arquivos no mesmo disco podem ser abertos. Em caso negativo, o disco pode estar danificado. Se for um disco rígido, contate o administrador ou o fornecedor de hardware do computador para obter assistência adicional.

Dados Adicionais 
Valor do erro: 00000000
Tipo de disco: 0
XML de Evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="49152">1005</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2025-01-30T04:10:56.8795015Z" />
    <EventRecordID>3623</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-5R7GBU8</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>flutterflow</Data>
    <Data>00000000</Data>
    <Data>0</Data>
  </EventData>
</Event>`



**_3 ARQUIVO DE ERRO**

`Nome do Log:   Application
Fonte:         Application Error
Data:          30/01/2025 01:10:56
Identificação do Evento:1000
Categoria da Tarefa:(100)
Nível:         Erro
Palavras-chave:Clássico
Usuário:       N/D
Computador:    DESKTOP-5R7GBU8
Descrição:
Nome do aplicativo com falha: flutterflow.exe, versão: 5.1.2.0, carimbo de data/hora: 0x679a68b4
Nome do módulo com falha: flutterflow.exe, versão: 5.1.2.0, carimbo de data/hora: 0x679a68b4
Código de exceção: 0xc000001d
Deslocamento da falha: 0x00000000007d3967
ID do processo com falha: 0x25f8
Hora de início do aplicativo com falha: 0x01db72ccda72aa8e
Caminho do aplicativo com falha: C:\Program Files\FlutterFlow\flutterflow.exe
Caminho do módulo com falha: C:\Program Files\FlutterFlow\flutterflow.exe
ID do Relatório: 7229179e-4bc0-47c2-9ea9-93b81c6bb3fd
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha: 
XML de Evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2025-01-30T04:10:56.8774968Z" />
    <EventRecordID>3622</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-5R7GBU8</Computer>
    <Security />
  </System>
  <EventData>
    <Data>flutterflow.exe</Data>
    <Data>5.1.2.0</Data>
    <Data>679a68b4</Data>
    <Data>flutterflow.exe</Data>
    <Data>5.1.2.0</Data>
    <Data>679a68b4</Data>
    <Data>c000001d</Data>
    <Data>00000000007d3967</Data>
    <Data>25f8</Data>
    <Data>01db72ccda72aa8e</Data>
    <Data>C:\Program Files\FlutterFlow\flutterflow.exe</Data>
    <Data>C:\Program Files\FlutterFlow\flutterflow.exe</Data>
    <Data>7229179e-4bc0-47c2-9ea9-93b81c6bb3fd</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>`

**Comment by MasterOTOKKY** [comment]
I had this problem on my home desktop computer. I figured out that my old
desktop did not have the minimum number of cpu cores as required for the
software. I purchased a new laptop that met the minimum CPU requirements
and it works fine.

-James

**Comment by paauloprado** [comment]
After switching to a new computer, FlutterFlow crashes when opening a project. Deleting the firebase-heartbeat and firestore folders in AppData temporarily fixes it, but they’re recreated and the app crashes again. I contacted support and they asked me to comment on this issue. Looking forward to a fix.🙏

**Comment by Sergii-Khomenko** [comment]
I have the same issue on Windows 10 22H2, 16GB RAM, a lot of free space on SSD. Flutterflow app 6.0.51 
Crash dump attached

[flutterflow.exe.8316.dmp](https://github.com/user-attachments/files/21341968/flutterflow.exe.8316.dmp)

**Comment by Raphaildest** [comment]
Também estou com o mesmo problema, flutterflow poderia solucionar isso!

**Comment by rscrm** [comment]
I'm having the same problem. FF just closes out of nowhere.

**Comment by tanasecosminromeo** [comment]
Same issue..

**Comment by Lotus49b** [comment]
Same issue here. Come on FF, your apathy to this problem isn't acceptable.

**Comment by abdounovich1995** [comment]
same error here

**Comment by slpatech** [comment]
Same here.

Edition	Windows 11 Home
Version	23H2
Installed on	‎10/‎22/‎2024
OS build	22631.6199
Experience	Windows Feature Experience Pack 1000.22700.1108.0

FlutterFlow 6.4.12

First install it wanted to download an update which worked. I was able to open FF and work for a very short while. Wen back the next day and FF crashes while loading. Uninstalled, Removed APPDATA and so on and reinstalled. Fails very shortly after downloading. Followed this suggestion...

Some Windows users may experience a crash. To fix this, install the Microsoft Visual C++ 2015–2022 Redistributable (both x64 and x86) from the official Microsoft site.

... made no difference.

Is this fixed in the release on Feb 3rd 2026?

The web.app is resource intensive and takes 100% of CPU. Would prefer that the desktop work. I like what I see so far... ;-)

Cheers!!

**Comment by berendsrick-coder** [comment]
Same issue here. Are there already any solutions?

**Comment by Sergii-Khomenko** [comment]
the issue still exists with latest version.
some fresh crash dumps attached

[flutterflow.exe.4728.dmp](https://github.com/user-attachments/files/25712586/flutterflow.exe.4728.dmp)
[flutterflow.exe.9772.dmp](https://github.com/user-attachments/files/25712584/flutterflow.exe.9772.dmp)
[flutterflow.exe.15272.dmp](https://github.com/user-attachments/files/25712585/flutterflow.exe.15272.dmp)
