### ISSUE TITLE
Flutterflow on windows doesn't launch

### ISSUE THREAD

**Issue by Perlo34** [FlutterFlow/flutterflow-issues#2610]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since this morning it is impossible for me to launch windows app , it only launch the update page

### Expected Behavior

Launch the app

### Steps to Reproduce

1.Launch Windows app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

### Context

Launch th windows app

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/92a165c0-1b00-4c68-ac26-2d4471ac58d7

### Environment

```markdown
- FlutterFlow version: 4.1.33
- Platform: Windows
- Browser name and version: Windows 11
- Operating system and version affected: Windows 11
```

**Comment by abbadabbatech** [comment]
It launches, but there is no google sigh in just email and password which I do not have, when I click create account and use the google signin there, it hangs and then crashes. A box pops up that is blank and then it hangs.

**Comment by JancarlosMartins** [comment]
I have the same problem

**Comment by veloz-app** [comment]
I've been trying to solve the same problem for 5 days, I've tried everything and nothing works.
 
- FlutterFlow version: 4.1.33
- Platform: Windows 10 pro 64bit
- 
![Anotação 2024-03-24 221821](https://github.com/FlutterFlow/flutterflow-issues/assets/164792275/001fd0af-9da2-4777-88f2-2c76139261c4)

**Comment by zouzoubel** [comment]
Same issue, I click on "Sign in with Google" and I get a blank window but it also shows this:
![localRunError](https://github.com/FlutterFlow/flutterflow-issues/assets/37817034/0ff8d9fe-090b-4f14-88a2-ae0ebefdb726)

**Comment by rzambroni** [comment]
Hi everyone, thanks for the report. We will investigate.

**Comment by Perlo34** [comment]
With uninstall and delete remaining files , i can now launch the app but i have an issue with version and the app don't have any update to do

**Comment by Perlo34** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/4fc89537-1124-4cbd-85f2-41993f16598e)

**Comment by duEuler** [comment]
> ![imagem](https://private-user-images.githubusercontent.com/136898815/318055507-4fc89537-1124-4cbd-85f2-41993f16598e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODY4ODQsIm5iZiI6MTcxMTc4NjU4NCwicGF0aCI6Ii8xMzY4OTg4MTUvMzE4MDU1NTA3LTRmYzg5NTM3LTExMjQtNGNiZC04NWYyLTQxOTkzZjE2NTk4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwODE2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYWYwZDlhYmQ5N2Q2ZTY2NzNkMTZlZTM5YWY0OTA3NzIyMDg2YTUxNjg5MjU5ZDJmZjYwMDY2MTAyNWZhZTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7I0gu_fkGKm9VKmhVpABWR4f8GZKyie-7Vl6O8FYVJE)


I'm facing the same issue; the project won't update.

**Comment by leighajarett** [comment]
These issues should be resolved in the next release tomorrow 🙂 Please re-file if you run into anything else

**Comment by veloz-app** [comment]
My problem has not yet been resolved with today's update 4.1.36,

I can't access the Windows app, the page loads and refreshes and closes by itself

**Comment by leighajarett** [comment]
We are not able to recreate this issue so it seems like it's project specific. Can you please reach out to our support team for help investigating?

**Comment by abbadabbatech** [comment]
The same for me. I still can not login via Google with the desktop on
Windows. Even after the upgrade yesterday. I even removed and downloaded
the package again and installed.

**Comment by leighajarett** [comment]
Just to confirm, you uninstalled the app on your Windows machine and then reinstalled it? Still don't see Google sign in?

**Comment by abbadabbatech** [comment]
That is correct. I see the login on the create login area and it still does
the same thing just blank screen. I will try it again in case I did not get
the latest. Is the Google login supposed to be on the login area and not
just the create account screen?

**Comment by MaxFF1800** [comment]
Hi @abbadabbatech, Max here from the FlutterFlow support team. Could you please share a screenshot of what you are seeing? Also, please make sure to uninstall the old version and install the new version from https://flutterflow.io/desktop. Once you have done so, if you still experience the issue, could you share a screenshot of what you see on your end? This would be super helpful in debugging the issue for you. Thanks!

**Comment by MaxFF1800** [comment]
@veloz-app Could you try to open another instance/window of the FlutterFlow desktop app by (middle mouse clicking) on the app in the taskbar? This should log you out of both sessions. If you are able to do so, could you try to login and see if the issue persists? Thank you.

**Comment by veloz-app** [comment]
I've tried and done this several times and it doesn't work, even with the most recent update.

I'll try to explain my problem to you step by step with how the error happens.

1- I uninstall flutterflow
2- I delete all files related to flutterflow from the PC
3 - I download the application again with the latest update
4- I install it on the local disk C: normally
5- I start the application for the first time, it opens and works normally.
6- When I close the program and open it again it gives this permanent error
7 - Every time I do this process, it only works once, closed, opened error

I hope I was clear about the error. It's been happening for 2 weeks and I can't use the Windows app
I made a video illustrating and demonstrating the error

[Video explaining the error.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/164792275/5b5b1501-e15a-49da-b25c-a1a1eb40873a)

**Comment by veloz-app** [comment]
I've tried and done this several times and it doesn't work, even with the most recent update.

I'll try to explain my problem to you step by step with how the error happens.

1- I uninstall flutterflow
2- I delete all files related to flutterflow from the PC
3 - I download the application again with the latest update
4- I install it on the local disk C: normally
5- I start the application for the first time, it opens and works normally.
6- When I close the program and open it again it gives this permanent error
7 - Every time I do this process, it only works once, closed, opened error

I hope I was clear about the error. It's been happening for 2 weeks and I can't use the Windows app
I made a video illustrating and demonstrating the error

[Video explaining the error.webm](https://github.com/FlutterFlow/flutterflow-issues/assets/164792275/06401f92-5587-4a7f-812b-d95b5bb7eaa9)

**Comment by leighajarett** [comment]
Since we are unable to recreate this issue, can you please reach out to our support team - support@flutterflow.io.

They will be able to collect more information regarding your system and help troubleshoot this further. Sorry for this experience, I know it can be super frustrating! Thank you so much!

**Comment by gorgulij** [comment]
+1. 
I cleaned, deleted, reinstalled, deleted Windows, formatted the hard drive, threw out the old one and bought a new computer – the same way... 
https://github.com/FlutterFlow/flutterflow-issues/assets/44435511/31f3b735-c4e5-4574-84e4-335c955d8c68

**Comment by gorgulij** [comment]
I cleaned, deleted, reinstalled, deleted Windows, formatted the hard drive, threw out the old one and bought a new computer – the same way...

https://github.com/FlutterFlow/flutterflow-issues/assets/44435511/f96de683-e57e-4fef-a976-7c9d5d0e7615
