### ISSUE TITLE
MacOS FlutterFlow app won't open

### ISSUE THREAD

**Issue by CallumCooky** [FlutterFlow/flutterflow-issues#2657]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I open the MAcOS app is get stuck in loading - doesn't launch 

### Expected Behavior

Expect the app to start

### Steps to Reproduce

1. Download MacOS app on Macbook Pro 2001 M1 Max
2. Install MacOS app 
3. Open MacOS app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Na

### Context

Trying to open the MacOS app

### Visual documentation

<img width="1453" alt="Screenshot 2024-04-04 at 12 57 54 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/165974071/2e78e9cf-2c79-4341-812d-a7bbf0a3de47">

### Environment

```markdown
- FlutterFlow version: N/a
- Platform:Desktop Macbook pro 2001
- Browser name and version:n/a
- Operating system and version affected: 4.4.1 (23E224) Sonoma
```

**Comment by bozzoleandro** [comment]
Hi @CallumCooky, thanks for your report, are you still experiencing this issue? I'm not able to reproduce it.

**Comment by zdd88** [comment]
我也遇到了同样的问题，使用可执行文件打开它报告的错误是：[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
#0      FirebaseFirestoreHostApi.queryGet (package:cloud_firestore_platform_interface/src/pigeon/messages.pigeon.dart:1130)
<asynchronous suspension>
#1      MethodChannelQuery.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:118)
<asynchronous suspension>
#2      _JsonQuery.get (package:cloud_firestore/src/query.dart:432)
<asynchronous suspension>
#3      initPlanDetails (package:flutter_webapp/src/backend/stripe.dart:414)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:518)
<asynchronous suspension>
#5      initCurrentUser (package:flutter_webapp/auth/firebase_user_provider.dart:234)
<asynchronous suspension>

**Comment by zdd88** [comment]
> 你好@CallumCooky，感谢您的报告，您还遇到这个问题吗？我无法重现它。

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
#0      FirebaseFirestoreHostApi.queryGet (package:cloud_firestore_platform_interface/src/pigeon/messages.pigeon.dart:1130)
<asynchronous suspension>
#1      MethodChannelQuery.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_query.dart:118)
<asynchronous suspension>
#2      _JsonQuery.get (package:cloud_firestore/src/query.dart:432)
<asynchronous suspension>
#3      initPlanDetails (package:flutter_webapp/src/backend/stripe.dart:414)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:518)
<asynchronous suspension>
#5      initCurrentUser (package:flutter_webapp/auth/firebase_user_provider.dart:234)
<asynchronous suspension>

**Comment by zdd88** [comment]
> 你好@CallumCooky，感谢您的报告，您还遇到这个问题吗？我无法恢复它。

我从官网下载的安装包，在macos系统上，双击安装，进入程序后会出现登录页面，登录账号后就一直在启动页，然后就没有任何的变化了。我尝试过重新启动系统，卸载重装，重启应用，都无法解决这个问题，我连换账号登录都不行了，一直卡在加载页

**Comment by HeikoKanzler** [comment]
It happens to me on my MacBook Air (M2) from time to time, but it always loads on my Intel MacBook Pro. I have to close the window then and try again; it loads on the second attempt.
(According to your Screenshot, you're on an Arm Machine, @CallumCooky ?

**Comment by CallumCooky** [comment]
Hi Heiko,

I'm not sure what an Arm Machine is?
My device is MacBook Pro 2021, M1. MacOS Sonoma 14.4.1.
The issue still occurs when I close the window and reopen again. I've
attempted this multiple times and reinstalled the app multiple times as
well.



[image: Screenshot 2024-04-08 at 10.09.57 AM.png]

**Comment by bozzoleandro** [comment]
Hi @CallumCooky, Can you please provide us with a blank project with the issue steps set up in it including the bug report code. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information.

**Comment by zcxiscoding** [comment]
我换成移动的网就可以了
