### ISSUE TITLE
General Properties : "! Is On-screen Keyboard visible" not working

### ISSUE THREAD

**Issue by jidylle** [FlutterFlow/flutterflow-issues#2864]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

General Properties : "! Is On-screen Keyboard visible" not working

### Expected Behavior

General Properties : "! Is On-screen Keyboard visible" working when it is activated.

### Steps to Reproduce

1- Add "! Is On-screen Keyboard visible"
2- Test on a mobile when the keyboard show

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ChcqB5YhOsdhE7rr+Y8JFhiYsKUAkRYIFjuxHUQoaHZPND+x/esnRQFJuZ9OrdkFqeWGammQ0+fzNm9z1O/VdaCubRZxl1ZYJbArhXl6Wb7bSEbWWRUFuGshQf0Cz37us3BBAPbJZSHAT12aUBu/LQgnbNbLzClcwAP39WZ7XrgfuQ0SLb3kNh1JWeC/v

### Context

General Properties : when you activate "! Is On-screen Keyboard visible" is not working.

### Visual documentation

General Properties : when you activate "! Is On-screen Keyboard visible" is not working.
![Projects_-_FlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/3247616/736ece88-acc5-4c3f-ac0b-a8dad2c94ee0)

### Environment

```markdown
- FlutterFlow version: 4.1.48
- Platform: web 
- Browser name and version: safari
- Operating system and version affected: ios
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @jidylle - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by jhonier93** [comment]
I am facing that error too!  " ! Is On-screen Keyboard visible"  it is not firing  when keyboard appears on screen.

**Comment by jhonier93** [comment]
@msusviela here are a blank project with the issue.  
[https://app.flutterflow.io/run/EMSU1WDlRwSSCp2vzOPT](blank project)

**Comment by jhonier93** [comment]
The problem is still there, we are still waiting for someone from the flutterflow team to review what we attached so that they understand the context but no one says anything

**Comment by rzambroni** [comment]
Hey @jhonier93, sorry about the delayed response. I'm trying to open the blank project link you provided, but for some reason is not loading on my end. 

Would you mind adding me as a collaborator to that project so we can make some test runs? (rzambroni@somniosoftware.com).

Thanks for your patience.

**Comment by jhonier93** [comment]
@rzambroni  thanks for response.  here the link of run app [https://app.flutterflow.io/run/EMSU1WDlRwSSCp2vzOPT](https://app.flutterflow.io/run/EMSU1WDlRwSSCp2vzOPT)       actually I added you as collaborator.

**Comment by Alezanello** [comment]
Hello!

I'm sorry for the late response regarding this issue. Are you still experiencing this bug after the recent FlutterFlow updates? I tested it myself by creating a new blank project with a TextField and an image below it. I set up conditional visibility for the image to hide when the keyboard is visible, and it is working as expected.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/265eb7e4-30c2-4035-9681-1efe39dd1e0a/7abc6709-9653-4247-9c0f-e329381318a9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNjVlYjdlNC0zMGMyLTQwMzUtOTY4MS0xZWZlMzlkZDFlMGEvN2FiYzY3MDktOTY1My00MjQ3LTljMGYtZTMyOTM4MTMxOGE5IiwiaWF0IjoxNzIxODU0ODkzLCJleHAiOjMzMjkyNDE0ODkzfQ.RAA8k5Vj90WlIYg-x8_Y6YMy3-nx2QAWcsV0auiJeT0 " alt="image.png" width="1111" height="329" />

[Video Keyboard Issue.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6ccc198c-f537-4213-8ebf-1cb9fcda5892/db7e0101-70a3-4693-8e8a-1edf2717c1f5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82Y2NjMTk4Yy1mNTM3LTQyMTMtOGViZi0xY2I5ZmNkYTU4OTIvZGI3ZTAxMDEtNzBhMy00NjkzLThlOGEtMWVkZjI3MTdjMWY1IiwiaWF0IjoxNzIxODU0ODkzLCJleHAiOjMzMjkyNDE0ODkzfQ.I-7vpmuYgSvQ4lP_Ql4Zp11tFrPX36dr2QdpndOxlg8)

<br>Let me know if is working correctly from your side or the issue still there for you!<br><br>Best regards,<br>Azanello

**Comment by GavinRF** [comment]
I'm having this same issue, was hoping it was going to be resolved here. Can I volunteer my project as a test case?

<img width="441" alt="Screenshot" src="https://github.com/user-attachments/assets/99f3bd18-6acd-4c41-a00a-1e76397a640c">

<img width="220" alt="screenshot" src="https://github.com/user-attachments/assets/f8f8e004-6c41-46a7-927c-44a394656669">
