### ISSUE TITLE
Deploying private API through cloud function gives wrong group

### ISSUE THREAD

**Issue by dennisdc** [FlutterFlow/flutterflow-issues#2930]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you have folders in the API calls and mark them private you will get MyGroupGroup instead of the name of the group folder in Firebase. It breaks all current api calls and the release. I have to manually change the create MyGroupGroup function to the name of my folder to make it work. Happens since update v4.1.53

### Expected Behavior

The group should be named after the folder

### Steps to Reproduce

create a group and add api calls in it
deploy to firebase

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

not based on a widget

### Context

Was trying to get a structure in my API calls

### Visual documentation

![Scherm­afbeelding 2024-05-17 om 15 58 20](https://github.com/FlutterFlow/flutterflow-issues/assets/2443367/5cfff34e-f814-4e4d-852e-d8ec7d2d806f)

### Additional Info

none

### Environment

```markdown
- FlutterFlow version: v4.1.53
- Platform: Mac
- Browser name and version: Chrome
- Operating system and version affected: //
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [X] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [X] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by Lalimec** [comment]
This happened to me yesterday. I took me whole day to figure that out since every damn debugging attempt showed no errors.

**Comment by stevey6404** [comment]
@Lalimec did you figure out a solution?

**Comment by itsstevenliu** [comment]
Seems like until FF fixes this, we will need to manually rename the function to match in Google Console and make sure we do not redeploy from FF

**Comment by Lalimec** [comment]
It was not like that last week though.

**Comment by itsstevenliu** [comment]
Yeah seems like someone at FF broke it...

**Comment by LWIdevteam** [comment]
We're having this same issue. Affects all api calls. FF please fix!

**Comment by sanjayelate** [comment]
How has this not been fixed yet or treated as a priority? It's broken all group APIs in my app

**Comment by MaxFF1800** [comment]
Try redeploying your private API cloud functions. This issue should be resolved.

**Comment by sanjayelate** [comment]
Have just tried that, still getting a 400 error message.

**Comment by itsstevenliu** [comment]
Same the code has not changed and I tried deploying from Mac and Web App.
You can access it via Google Console.

This should say createStripeConnectGroup. 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/151034963/e4fce530-3459-4f0b-8e3e-6474fe0b4ccc)

**Comment by ignalauret** [comment]
Hey @dennisdc thanks for your report. I just followed your steps from a blank project and I got the correct name for the Group on the api_manager.js file. Is this issue still happening if you download the code again?

**Comment by dennisdc** [comment]
Hey @ignalauret , still getting the same result when I deploy my API's to Firebase. I downloaded a new version of the Desktop app.

What happens is the file api_manager.js in my Cloud function called ffPrivateApiCall is not getting the right groups of calls, that represent the folders in my app in the Flutterflow editor. After deploy the first function after the new group, that creates the group are all called MygroupGroup.

Also tested this from the web editor, gives the same result.

thanks for looking into this.

**Comment by itsstevenliu** [comment]
Agree with @dennisdc. Downloaded latest Mac and also used Web to publish. 
Tried duplicating the group and still this new group is being deployed with the wrong name (I.e. createMyGroupGroup)

**Comment by MaxFF1800** [comment]
Just a quick update: **our team has successfully pushed the update to fix the issue**. 🎉

You will need to redeploy your private API call 🚀. Once you do, everything should be working smoothly. Please confirm if this resolves the issue on your end.

We apologize for any inconvenience caused and appreciate your patience.

Thanks,
Max

**Comment by dennisdc** [comment]
@MaxFF1800 will try, do we need to download a new desktop app?

**Comment by MaxFF1800** [comment]
@dennisdc you may need to download the new desktop app (it should auto update) Just tested on the latest release and it deploys correctly
