### ISSUE TITLE
Error compiling project with google maps. Deploy app store

### ISSUE THREAD

**Issue by lleo132** [FlutterFlow/flutterflow-issues#3020]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello team! After adding the Google Maps widget, the project can no longer be compiled by Codemagic, I tried to start a local compilation and the same error was returned.

### Expected Behavior

The application should be compiled, shipped, and run. In test mode everything runs fine

### Steps to Reproduce

1. Add the Google Maps widget and make all necessary settings in Firebase
2. Try uploading to apple store or compiling in vscode/xcode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Sjs/l5ZV2pbxE1s/yacFFmSQWNmInaucolsJQEEodfeutPaQlXOj9YlRuOOGhdG4/IWCI8Tkz+fOLuePDDsItPiiZQL57yMxuUT3Le3O5Wrq1EaWOfnEmN/xmN22HzbWGnhMlAPRtR1ktw02YHvPIFy3qO5TuCmoZG8miGKj4jla8GwzOXn0Jg1ZSfCvr

### Context

This problem affected all my users who use the IOS system

### Visual documentation

<img width="644" alt="Captura de Tela 2024-05-30 às 16 48 45" src="https://github.com/FlutterFlow/flutterflow-issues/assets/118861389/b196844c-4b0e-41ca-ac4d-2fb771b52e81">
<img width="1440" alt="Captura de Tela 2024-05-30 às 17 15 28" src="https://github.com/FlutterFlow/flutterflow-issues/assets/118861389/b1cf7ed0-d8de-45c8-83fe-c19eda408d80">

### Environment

```markdown
- FlutterFlow version: 4.1.53
- Platform: Macos
- Browser name and version:
- Operating system and version affected: IOS
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [X] I was using flutterflow from multiple devices
- [X] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [X] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [X] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by paulperez-dev** [comment]
Hi @lleo132! Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information.<br><br>If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by lleo132** [comment]
@paulperez-dev Unfortunately I still have the problem and now another message
![Uploading Captura de Tela 2024-06-03 às 12.38.30.png…]()

**Comment by lleo132** [comment]
@paulperez-dev Unfortunately I still have the problem and now another message
<img width="901" alt="Captura de Tela 2024-06-03 às 12 38 30" src="https://github.com/FlutterFlow/flutterflow-issues/assets/118861389/65b3fe42-12c1-433b-ad8c-2e3d649df7da">

**Comment by lleo132** [comment]
Hi @paulperez-dev, Unfortunately the problem has not been fixed. I found some similar reports about this problem and so I believe that Google Maps is the cause.
https://github.com/FlutterFlow/flutterflow-issues/issues/2494

**Comment by paulperez-dev** [comment]
Can you please reproduce the issue on a blank project and share the bug report code again?

**Comment by paulperez-dev** [comment]
The issue shared is closed and points to a problem with the package.

**Comment by lleo132** [comment]
@paulperez-dev Após a atualização do flutterflow no dia de hoje, conseguir fazer o deploy com sucesso, aparentemente se tratava de algum problema nos dataTypes. Considero assim como resolvido!

**Comment by paulperez-dev** [comment]
Thanks for the confirmation!
