### ISSUE TITLE
Unable to create a branch. Get Error.

### ISSUE THREAD

**Issue by charliefabley** [FlutterFlow/flutterflow-issues#3180]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I try and make a branch I get an error in red at the bottom of the FF screen

### Expected Behavior

The branch is created.

### Steps to Reproduce

Attempt to make a new branch from main

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KkvLlw4x2ruZE7rruK/lVtCYWNjsja7sslsJtbwAdNYvpG7k+XM+lYkRtZM+/TFZYME2Wp2oW3NrmufP1K/IDEyycQaJ5yYdyWA7/Wj+WRJisFJWgSn9tI+9RGmmO4aarpx0kALZiLFEu7WCqAfC/TT3tQpD1IlUsDq/LZO4=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/153652817/e5a6fc5b-b058-49a6-9a54-68017eb320e8)

### Environment

```markdown
- FlutterFlow version: Latest
- Platform: Windows and Web
- Browser name and version: Chrome and Windows. 
- Operating system and version affected: 12
```

**Comment by rzambroni** [comment]
Hey @charliefabley, thanks for the report, we fixed an issue in beta about this so it is not supposed to exist anymore, let me follow up internally and see what might be happening here.

**Comment by rzambroni** [comment]
Hey, can you check if the issue still persists and let us know? Don't forget to restart the app before trying. 

Thanks

**Comment by charliefabley** [comment]
No, it has not.

**Comment by charliefabley** [comment]
Sorry what I meant by my last reply is that it is not fixed  - it does not
come up with an error, but it just times out after a while.

**Comment by MaxFF1800** [comment]
@charliefabley  We’ve just implemented a manual overwrite to resolve the issue. Could you please try again and confirm if the changes were successful? Thank you.

**Comment by karlisbroks** [comment]
Issue still persists :(

**Comment by christianschoenmakers** [comment]
Same issue here

**Comment by lobo1111** [comment]
same here

**Comment by Morne004** [comment]
Exactly the same issue here, only on some of my projects though.
Both on Desktop (Windows) and WebApp.
