### ISSUE TITLE
Chart Widget X and Y axis values are resetting

### ISSUE THREAD

**Issue by curiousrohan1** [FlutterFlow/flutterflow-issues#3553]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I use the Chart widget and I set the X-axis and Y-axis to the desired fields from an array of objects, the dropdowns for each axis reset to "unset" after a few seconds. 

### Expected Behavior

I expected the Char's axis dropdowns to remember what I entered into them.

### Steps to Reproduce

1. Create a page.
2. Add a Chart widget to that page.
3. Set the X and Y axis dropdowns to values from a collection of objects.
4. Observe the dropdowns (after a short amount of time, they will reset to "unset").

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/HluIhgoeEG0bqJLMZAhR8kQ2InarsvhOpDTUoaF5SuE5kLbuvSXBFVcMOIewhmKGL9jXMGpMLQkoXPU/UrFzWEQ5Rf1rlxWzniQmOXMoSrBs60fmpSI9tjI0C/4Jmn2BVTJvJ2ZXMtig/GSw==

### Visual documentation

https://github.com/user-attachments/assets/42a62e47-ae78-4360-9fbb-4e8951add16b

graphTime and starRating are integer fields.

### Environment

```markdown
- FlutterFlow version: v4.1.79
- Platform: MacOS Laptop
- Browser name and version: Chrome 127.0.6533.89
- Operating system and version affected: macOS 14.5 (23F79)
```

### Additional Information

These charts provide a core feature of my app to provide the user insight into patterns of their behavior; please consider this a P1.

**Comment by SharpQuenty** [comment]
I have a reset issue for the "Label interval".

**Comment by Alezanello** [comment]
Hello!

First of all, I'm sorry you are experiencing this issue. On the other hand, could you please try to remove the chart and create a new one from scratch, adding the values again to see if this still happens? In the meantime, I will share the video you sent with the engineering team for a deeper look.

Best regards,<br>Azanello

**Comment by omegamaster86** [comment]
AppStateで対応したらチャートが表示されました。
firebaseのデータをAppStateに置き直せばうまくいく可能性があります。

**Comment by curiousrohan1** [comment]
Hello,

Thanks for the suggestion. Unfortunately, I already tried removing the chart and creating a new one from scratch, but the problem didn't go away.

**Comment by curiousrohan1** [comment]
Apologies for closing this, I accidentally pressed the wrong button.

**Comment by TimNjeru** [comment]
I had a similar issue but I noticed that my xValues were not integers. This disappeared after I corrected that.

**Comment by antoniobno1** [comment]
Hi, I am having the exact same issue... https://github.com/FlutterFlow/flutterflow-issues/issues/3619

Also tried redoing the graph from scratch. I have also been able to deploy before it gets reset, that's why I know my data is good.

**Comment by Alezanello** [comment]
Hello again!

I've confirmed the issue and will be recording it to send to the engineering team for a fix. Thank you very much for bringing this to our attention!

**Comment by antoniobno1** [comment]
Thank you so much @Alezanello

**Comment by antoniobno1** [comment]
Hi @leighajarett @br0nk @Alezanello, I´m still having this issue, has this gone into production yet?

**Comment by antoniobno1** [comment]
> Hi @leighajarett @br0nk @Alezanello, I´m still having this issue, has this gone into production yet?

Im on
FlutterFlow v4.1.83+ released August 20, 2024
Flutter version is 3.22.2

**Comment by turisouza** [comment]
I'm facing the same issue. Any idea of ​​a fix?

Im on
FlutterFlow v4.1.83+ released August 23, 2024
Flutter version is 3.22.2

**Comment by GabrielFelix10** [comment]
@leighajarett @br0nk @Alezanello 
 
 Same error here guys, can you give us some update status ?

**Comment by turisouza** [comment]
They closed the bug without solving it.

I reopened the complaint, let's see if we can get their attention.

Here's the link: https://github.com/FlutterFlow/flutterflow-issues/issues/3685

**Comment by tarakiga** [comment]
Same issue

**Comment by MartinRamdane** [comment]
I'm facing the same issue, any updates ?

**Comment by gaetanloriot** [comment]
Also facing this silly issue and because of this, the chart is basically useless.

**Comment by RikHaanen** [comment]
I also have the same issue with the "Label interval".
I set the 

https://github.com/user-attachments/assets/240f7bd8-41f2-4d88-8ed3-20c5eea36e11

**Comment by RikHaanen** [comment]
I build a work around for  my problem (being the interval being reset to 10):
I build my own Y and Y labels with columns, rows and stacks of labels. See video for inspiration. 
![Untitled](https://github.com/user-attachments/assets/561f0114-2b8d-4582-8bc8-1445f6687a1e)

Uploading Recording 2024-10-30 150936.mp4…

**Comment by leostaclara** [comment]
I have exactly the same problem in Flutterflow when I use 
I use the chart and try to define it in the chart properties Y Axis > Properties
label interval the value is not defined, returning to 10. The records are dates in the format M/d H:mm

**Comment by zhenyu-hong** [comment]
I'm facing the same issue

**Comment by taggxyz** [comment]
I'm still facing this issue
