### ISSUE TITLE
Local Run Build Fails with 'UnmodifiableUint8ListView' not found

### ISSUE THREAD

**Issue by laughingbuddha24** [FlutterFlow/flutterflow-issues#4458]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Local run build is failing with Android Studio on Windows 11 with the following errors:

Launching lib\main.dart on sdk gphone x86 in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDebug'...                          
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(guid));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
  factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:5:7: Error: Method not found: 'UnmodifiableUint8ListView'.
      UnmodifiableUint8ListView(Uint8List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:7:7: Error: Method not found: 'UnmodifiableUint32ListView'.
      UnmodifiableUint32ListView(Uint32List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:9:7: Error: Method not found: 'UnmodifiableInt32ListView'.
      UnmodifiableInt32ListView(Int32List(0));
      ^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Dom\AppData\Roaming\FlutterFlow\flutterflow\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
Running Gradle task 'assembleDebug'...                             15.0s
Error: Gradle task assembleDebug failed with exit code 1

### Expected Behavior

I expect the app to load in the Android Studio emulator

### Steps to Reproduce

1. go to Local Run
2. select a device
3. click Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Skcrq2ItNvttZ+KXqdcAxnSQWOUA5aLgriOtqEBI3faKvELNyXOjASEhVXd+/TAl2Ilv9nTk00NKOv/zpCOQHAyyBGYBMzLtyVD3gcEatMsWLOpewXXR9L8VVJEuVyJ6Jnx17HMhoV14hwV2yOe6taC3fGZTtOTANPP+hIdnLpHDlAi+6Xn0Jg1ZSfCvr

### Visual documentation

![Screenshot 2024-10-23 120043](https://github.com/user-attachments/assets/cf3fbcc2-7d27-4310-89db-d5c9741f8ea9)

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform: Android
- Browser name and version: n/a
- Operating system and version affected: Windows 11 Home
```

### Additional Information

This is a breaking issue that has halted development as we can't test any new work. Please assign the highest priority.

**Comment by ajaniewiem** [comment]
I experience exactly the same issue after yesterday's flutter update.

**Comment by YsquanirSq** [comment]
Same for me, started happening after the Flutter upgrade yesterday. Same build error.

**Comment by CONONIC** [comment]
Also experiencing this exact issue

**Comment by ajaniewiem** [comment]
Are you using one of these dependencies: `device_info_plus` `package_info_plus` `share_plus`? I found out that I only have these custom dependencies that use `win32` and they might be the reason.

**Comment by itsstevenliu** [comment]
Same issue. I'm not using  - here are my dependencies
![image](https://github.com/user-attachments/assets/7fb183b0-e447-4db5-b4b4-4cc6c030e68f)

**Comment by ajaniewiem** [comment]
I updated my dependencies to the following and the local run is working again 🎉 `share_plus: ^10.0.2` `package_info_plus: ^8.1.0` `device_info_plus: ^11.1.0`

I recommend you check all your dependencies if they use `win32` and update them. You can easily do this by going to Settings > Project Dependencies > Custom dependencies and go to the pub.dev by pressing the icon for each of them. Then check the dependencies of this package in the right column.
<img width="1789" alt="Screenshot 2024-10-23 at 11 57 42" src="https://github.com/user-attachments/assets/2dd7601d-0901-4eb6-8665-75029b8800c1">
<img width="1220" alt="Screenshot 2024-10-23 at 11 58 37" src="https://github.com/user-attachments/assets/2b3fb22b-ead0-431a-ad3b-943d522ea7fb">

**Comment by paulperez-dev** [comment]
Hi @everyone,

Could you please try the solution that **@ajaniewiem** mentioned and let us know if it works for you?

**Comment by whatsake** [comment]
I had the same issue i.e Local/Pub/Cache/hosted/pub.dev/archive-3.4.10/lib/src/bzip2/bzip2.dart:7:7: Error: Method not found: 'UnmodifiableUint32ListView'.

What did was to add the latest archive package to my project https://pub.dev/packages/archive/versions/3.6.1.
Turns our that after the flutter update, I didnt even have the archive package anymore.

This sorted my issue! Hope it does for you as well!

**Comment by itsstevenliu** [comment]
@paulperez-dev, I checked all my dependencies and none of them directly use web32. The only dependency which used another dependency that relied on web32 was html_editor_enhanced: ^2.6.0 which relied on file_picker: ^8.1.3 

However adding the latest archive package like @whatsake suggested helped made local run work

**Comment by iwanwmys** [comment]
Same issue, the solution from @whatsake seemed to work for me.

**Comment by Severinius-MUC** [comment]
Solution from @whatsake worked for me. Thanks

**Comment by jaymutzafi** [comment]
Forgive my ignorance, how do i add this package? 

I first tried adding things here but it errors for anything I try:
<img width="438" alt="image" src="https://github.com/user-attachments/assets/ed4821b3-88b0-41ff-a2f2-2386fd66b3d2">

<img width="569" alt="image" src="https://github.com/user-attachments/assets/cfc677c4-714b-4f99-8557-58378a6a7ba9">

I then tried adding this but I still can't build local run and get the same error with Uint8ListView:
<img width="694" alt="image" src="https://github.com/user-attachments/assets/73378077-adcf-4dd6-a2f6-ccb929ebdbfd">

Any explicit instructions would be appreciated.

**Comment by Alezanello** [comment]
Jay you can add it in any custom action you have like this:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f67194ba-ba67-40f1-8ba8-236033926c79/cbde87f1-51eb-4db9-abe6-9d95e290bc72?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mNjcxOTRiYS1iYTY3LTQwZjEtOGJhOC0yMzYwMzM5MjZjNzkvY2JkZTg3ZjEtNTFlYi00ZGI5LWFiZTYtOWQ5NWUyOTBiYzcyIiwiaWF0IjoxNzI5NzEwMzM2LCJleHAiOjMzMzAwMjcwMzM2fQ.LOfLxZS3GznppXrM7Oo_MbY0s7c-pA6vu6wwEI1QUtI " alt="image.png" width="1601" height="615" />

**Comment by CONONIC** [comment]
solution from @ajaniewiem worked for me

**Comment by laughingbuddha24** [comment]
The solution from @whatsake worked for me. So is this a FF bug or do we need to keep the archive: ^3.6.1 dependency there permanently?

**Comment by oleksii-it** [comment]
Have the same issue!!!!
I don't have any custom dependencies. Just project.
FF... why constantly we have such issues?????

**Comment by whatsake** [comment]
@oleksii-it try to add the latest dependency of archive anyway (via a blank custom widget or via the dependency page) and see if this fixes it.

**Comment by fubr** [comment]
> @oleksii-it try to add the latest dependency of archive anyway (via a blank custom widget or via the dependency page) and see if this fixes it.

I have tried this, i added the custom function to the main function too and still nothing. archive is showing in custom code dependencies with the version ^3.6.1

Any other ideas? I have tried another one of my projects at its not needed in my other project so it seems to be specific to a certain library

**Comment by whatsake** [comment]
@oleksii-it can you send s screenshot of the error?

**Comment by itdar** [comment]
`./flutter upgrade --force` in {flutterDir}/bin

it worked.

**Comment by leighajarett** [comment]
Hi everyone, this should be resolved now. Please let me know if you're still experiencing this issue!

**Comment by itdar** [comment]
I still have same issue, should I re-install flutterflow on laptop? @leighajarett

**Comment by itdar** [comment]
Hi leighajarett, I still have same issue.

I removed flutter, dart and cocoapods (re-installed). 
I also upgrade xcode and simulator ios version (17.5 -> 18.0)
What should I do more? @leighajarett 

```
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `FirebaseFirestore` from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `11.2.0`
firebase_analytics: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.2.0' defined in 'firebase_core'
Downloading dependencies
Installing AppAuth (1.7.5)
Installing Firebase (11.2.0)
Installing FirebaseAnalytics (11.2.0)
Installing FirebaseCore (11.2.0)
Installing FirebaseCoreExtension (11.2.0)
Installing FirebaseCoreInternal (11.4.2)
Installing FirebaseFirestore (11.2.0)
Installing FirebaseFirestoreAbseilBinary (1.2024011602.0)
Installing FirebaseFirestoreBinary (11.2.0)
Installing FirebaseFirestoreGRPCBoringSSLBinary (1.65.1)
Installing FirebaseFirestoreGRPCCPPBinary (1.65.1)
Installing FirebaseFirestoreGRPCCoreBinary (1.65.1)
Installing FirebaseFirestoreInternalBinary (11.2.0)
Installing FirebaseInstallations (11.4.0)
Installing FirebaseMessaging (11.2.0)
Installing FirebaseSharedSwift (11.2.0)
Installing Flutter (1.0.0)
Installing GTMAppAuth (4.1.1)
Installing GTMSessionFetcher (3.5.0)
Installing Google-Mobile-Ads-SDK (11.2.0)
Installing GoogleAppMeasurement (11.2.0)
Installing GoogleDataTransport (10.1.0)
Installing GoogleSignIn (7.1.0)
Installing GoogleUserMessagingPlatform (2.6.0)
Installing GoogleUtilities (8.0.2)
Installing PromisesObjC (2.4.0)
Installing app_links (0.0.1)
Installing firebase_analytics (11.3.3)
Installing firebase_core (3.6.0)
Installing firebase_messaging (15.1.3)
Installing google_mobile_ads (5.1.0)
Installing google_sign_in_ios (0.0.1)
Installing kakao_flutter_sdk_common (1.9.6)
Installing leveldb-library (1.22.5)
Installing nanopb (3.30910.0)
Installing path_provider_foundation (0.0.1)
Installing pointer_interceptor_ios (0.0.1)
Installing shared_preferences_foundation (0.0.1)
Installing sign_in_with_apple (0.0.1)
Installing sqflite (0.0.3)
Installing url_launcher_ios (0.0.1)
Installing webview_flutter_wkwebview (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 16 dependencies from the Podfile and 42 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).

[!] The `Runner [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig'. This can lead to problems with the CocoaPods installation

[!] The `Runner [Profile]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
Launching lib/main.dart on iPhone 16 Plus in debug mode...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
ios/Runner/AppDelegate.swift uses the deprecated @UIApplicationMain attribute, updating.
Running pod install...                                              3.8s
Running Xcode build...                                          
Xcode build done.                                           110.4s
Failed to build iOS app
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.

Could not build the application for the simulator.
Error launching application on iPhone 16 Plus.
```

**Comment by fubr** [comment]
> Hi everyone, this should be resolved now. Please let me know if you're still experiencing this issue!

I am still having the same issue. i upgraded to ff v5.0.9+ and the problem still exist for me. I created a action and added archive: ^3.6.1 but that made no difference. heres a copy of the error..

Launching lib\main.dart on SM G991U1 in debug mode...
Upgrading build.gradle
Running Gradle task 'assembleDebug'...                          
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:32:9: Error: 'UnmodifiableUint8ListView' isn't a type.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:52:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(guid));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:56:31: Error: Method not found: 'UnmodifiableUint8ListView'.
  factory Guid.zero() => Guid(UnmodifiableUint8ListView(Uint8List(16)));
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../../Local/Pub/Cache/hosted/pub.dev/win32-5.4.0/lib/src/guid.dart:100:17: Error: Method not found: 'UnmodifiableUint8ListView'.
    return Guid(UnmodifiableUint8ListView(Uint8List.fromList(guidAsBytes)));
                ^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot_program failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Woodw\AppData\Roaming\FlutterFlow\flutterflow\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Running Gradle task 'assembleDebug'...                             12.5s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by Zoka98** [comment]
updating the package win32 to the latest version fixed the issue for me

**Comment by itdar** [comment]
Maybe you did the same as me @Zoka98  (It's not about Custom Function or something)
I fixed after updating flutter project dir (My FlutterFlow project dir in local laptop).

I think you should find your FlutterFlow project dir in your local pc, and do this commands for updating @fubr 
```
flutter clean
flutter pub get
```

Local Run is not for free function in FlutterFlow tho

**Comment by kaymasse** [comment]
Hello, I am experiencing the same error upon local run.

Regarding the fixes proposed above:
- I have no custom dependencies (referring to https://github.com/FlutterFlow/flutterflow-issues/issues/4458#issuecomment-2431592694)
- I created a blank Custom Widget with dependency archive: ^3.6.1, but this did not solve the problem.

Would you have any other suggestions? Can I share something else which would help in the debugging?

---

The device logs:
Updating local specs repositories

CocoaPods 1.16.1 is available.
To update use: `gem install cocoapods`

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.16.1

Analyzing dependencies
Downloading dependencies
Installing Flutter (1.0.0)
Installing app_links (0.0.1)
Installing package_info_plus (0.4.5)
Installing path_provider_foundation (0.0.1)
Installing shared_preferences_foundation (0.0.1)
Installing sign_in_with_apple (0.0.1)
Installing sqflite (0.0.3)
Installing url_launcher_ios (0.0.1)
Installing video_player_avfoundation (0.0.1)
Installing wakelock_plus (0.0.1)
Installing webview_flutter_wkwebview (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 11 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
Launching lib/main.dart on iPad (10th generation) in debug mode...
Upgrading contents.xcworkspacedata
Updating project for Xcode compatibility.
Upgrading project.pbxproj
Upgrading Runner.xcscheme
Upgrading Info.plist
Removing script build phase dependency analysis.
Adding input path to Thin Binary build phase.
Running pod install...                                          ios/Runner/AppDelegate.swift uses the deprecated @UIApplicationMain attribute, updating.
   880ms
Running Xcode build...                                          
Xcode build done.                                            9.0s
Failed to build iOS app
Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/win32-5.5.0/lib/src/guid.dart:32:9: Error: Type 'UnmodifiableUint8ListView' not found.

Could not build the application for the simulator.
Error launching application on iPad (10th generation).

**Comment by damianfraire** [comment]
facing the same issue but the solution proposed by @itdar worked for me. Just going to the project and doing a flutter clean and flutter pub get

**Comment by fubr** [comment]
Type this line of code in your android studio terminal. That should fix the problem. it worked for me. 

flutter pub upgrade win32

**Comment by kaymasse** [comment]
Thank you very much @damianfraire and @fubr! 🙏 I run all 3 commands from VS Code and the local run works now. Hurray!!! 🥳

Note for those to whom it can be helpful: although it did not prevent the run from working, the original error kept popping up for another I would say 10 minutes, and then seems to have stopped showing up. This was the error:
<img width="760" alt="Error 1" src="https://github.com/user-attachments/assets/9d6aff53-f484-4fbc-8b2b-fe138fca2600">

**Comment by fubr** [comment]
> Thank you very much @damianfraire and @fubr! 🙏 I run all 3 commands from VS Code and the local run works now. Hurray!!! 🥳


You're welcome! Glade we found the solution

**Comment by kaymasse** [comment]
I just wanted to mention to the FlutterFlow team that I still get this message popping up at the local run. It does not block the run though.
<img width="760" alt="Error 1" src="https://github.com/user-attachments/assets/c72985e5-9094-4c99-8317-ef50cca83d6c">

**Comment by esseitalo** [comment]
The solution from  @itdar plus `flutter pub upgrade` worked for me. Thank you very much!

**Comment by aaahariri** [comment]
> Type this line of code in your android studio terminal. That should fix the problem. it worked for me.
> 
> flutter pub upgrade win32

This fixed suggested by @fubr helped solve the issue for me! Thanks!

What I did was:
- Open VS Code project from FlutterFlow Test area.
- Run the code within the local environment.
- Try to run local mode.

**Comment by jimnastic** [comment]
Hi @itdar 
I tried 
`flutter clean 
and
flutter pub get`
but got error
`Note: vm_service is pinned to version 13.0.0 by flutter_goldens from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because flutter depends on flutter_goldens from sdk which depends on vm_service 13.0.0, vm_service 13.0.0 is required.
So, because flutter depends on vm_service 14.2.5, version solving failed.
`
As far as I know, I don't use these packages so not sure where the dependency is coming from. Any ideas?
