### ISSUE TITLE
'LatLng' and 'FFUploadedFile' error after upgrading to latest version v12

### ISSUE THREAD

**Issue by Mr-AT-Thompson** [FlutterFlow/flutterflow-issues#5239]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After the update this morning we got bugs with 'FFUploadedFile' and 'LatLng' that we never had before:

Undefined class 'FFUploadedFile'. Try changing the name to the name of an existing class, or creating a class with the name 'FFUploadedFile'. - we are simply using FFUploadedFile as the return type and creating a variable (final file = FFUploadedFile(bytes: bytes);)

The name 'LatLng' isn't a type, so it can't be used in an 'as' expression. Try changing the name to the name of an existing type, or creating a type with the name 'LatLng'. on line 3038 - our code only has 36 lines.

### Expected Behavior

These errors should not be present. After the update FFUPloadedFile is not recognized and LatLng errors are thrown even though we are not using it in that file context

### Steps to Reproduce

Using FFUploadedFile and I am not sure why LatLng errors are thrown as we are not using anything related to lat or lng in the function

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlfLl5YZOm7xc7arpbcAxmicsJkAnaucolsFTb0sbIrHmG7YAW/SkQE9WZ7yhdH03eFmZ+T0d+eiPuebIN8YBBxWuf6o/1KphETzgRnOib8XRPLiWX3RBHtpKCFyP17uFkB0kC7dfclINw2CUftmtcBDsQLG3PGo7JeWJBKfLo3fuQ0SLb3kNh1JWeC/v

### Visual documentation

![Screenshot 2025-01-08 at 12 31 43](https://github.com/user-attachments/assets/faf6ce0e-73d6-4777-83f1-76793010575f)
![Screenshot 2025-01-08 at 12 31 24](https://github.com/user-attachments/assets/4cc0e53b-9905-436d-99bf-3da728f9feff)

### Environment

```markdown
- FlutterFlow version: v12
- Platform: All
- Browser name and version: Chrome latest
- Operating system and version affected: Mac and Windows
```

### Additional Information

These errors came up right after the update and is stopping us from deploying which is causing issues with our clients.

**Comment by Morne004** [comment]
Having exactly the same issues with custom code in my projects since the latest updates to Flutterflow. Seeing many comments on Reddit and Flutterflow community but not seeing any responses. hoping someone from Flutterflow responds soon.

**Comment by syg-eliseu** [comment]
The error came after the January 7th update. 

The update would resolve an issue I reported in this issue [ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/4998).

Even check out the comment I described in ticket [#4998](https://github.com/FlutterFlow/flutterflow-issues/issues/4998), the update solved one problem and generated another.[](url)

**Comment by Alezanello** [comment]
Hi there!

Thank you for sharing your project details with us. I’ve reviewed the project using the bug report code you provided and can confirm the issue. I’ll escalate this to our engineering team for further investigation.

We appreciate your patience as we work on resolving this. Please feel free to reach out if you have any additional details or questions in the meantime.

**Comment by bbeckford** [comment]
Also having the identical issue to @syg-eliseu 

![image](https://github.com/user-attachments/assets/b84280c7-b6af-4197-b497-08514b52e70f)

**Comment by drodriguez-gol** [comment]
Hi guys!

It seems that there is a solution to solve the custom functions dependencies bug from flutterflow.

If the project has a library published in its dependencies, just update the version of the library in the project and it allows to debug the custom functions again.

It has helped me and now I don't have any bug and I can work with flutterflow app or web with total normality.

I hope it helps.

Regards, David.

**Comment by syg-eliseu** [comment]
@drodriguez-gol, Thank you for your tip but unfortunately it didn't work for me. I released a new version of my library and updated the project that depends on it but nothing changed. Grateful

**Comment by olivierb24** [comment]
Same for me...I get compilation errors everywhere. In fact, adding a library to my project broke everything.


![image](https://github.com/user-attachments/assets/b82932d2-4081-4e97-8cbc-19dc2f34c366)

**Comment by Ivans-Diniz** [comment]
This issue is causing major disruptions for my team. We are unable to proceed with a critical app release due to the breaking changes. We are currently stuck trying to adapt to these changes.

The delay is impacting our project timeline and client commitments. This situation also raises serious concerns about the reliability of the platform for future projects. 

Quick resolution would be greatly appreciated.

**Comment by bbeckford** [comment]
This is also causing severe issues for my team, putting strain on our relationships with clients. I have 1 app literally ready to launch but I can't due to this issue.

We need a lot more info from you guys at FF - you have to be faster and more communicative in situations such as this.

**Comment by Mr-AT-Thompson** [comment]
We just got a new Flutterflow Version release which seems to have fixed the LatLng issue - @Ivans-Diniz and @bbeckford - just check if you don't have a pending update for FlutterFlow

**Comment by syg-eliseu** [comment]
For me, this update on January 9th did not correct this problem, the error continues to appear for me in the project error panel. 

![image](https://github.com/user-attachments/assets/acad82b0-3925-44dc-acca-f282186ed14d)


I used the web version of FlutterFlow to test the update, since my Windows version doesn't open due to an issue abandoned by the FF team.

**Comment by Onesizefitsall** [comment]
The issues continue here also, the Jan 9 didn't help at all, a dirty workaround that I did is during the docker process (it's a web project) I set to copy all the files from dependencies\ff_commons\lib\flutter_flow to  \lib\flutter_flow and that makes the issue go away. So I'm able to compile externally at least, but not able to use the debug and run features on flutterflow

**Comment by bbeckford** [comment]
On Flutter web, version _FlutterFlow v5.0.0+ released January 10, 2025_ this issue is fixed - BUT it's introduced yet another strange issue which I've submitted another issue for - #5252

Now I still can't compile due to more errors seemingly caused by the new libraries system.

I get this issue which suggests there are errors in one of my custom functions, turns out it just flags whatever custom function ends up last in the resultant `lib\flutter_flow\custom_functions.dart` file.

![image](https://github.com/user-attachments/assets/85295221-81b9-4f46-9b11-b72ce4a6cdc3)

Then clicking the bug icon inside that custom function in the FF UI yields a big list of errors that are nothing to do with that individual custom function:
![image](https://github.com/user-attachments/assets/0a8a0c3a-dfc7-4b57-b0a6-7b87b248c096)

Again when I download the code I have no issues, so this is something to do with the on-the-fly compiler that the FlutterFlow UI uses. My instinct is that this has something to do with importing multiple libraries that make use of library values, the `FFLibraryValues` class.

Again back to square one trying to get another bug fixed - all the while I have clients waiting...

**Comment by carlosmachina** [comment]
Trying to build on FlutterFlow web:

![image](https://github.com/user-attachments/assets/92348059-870e-4c7b-a589-7b8addfea5ec)

And on desktop:

![image](https://github.com/user-attachments/assets/ee355b62-bad5-423b-96d9-248f6a5287ef)

But, well, maybe I'm on the wrong here for trying to work with a tool I've been paying for.

Certainly, is not the case that a guy 2 comments before me have already shown a viable way to fix the issue on FlutterFlow's side (at least until someone on the tech team explains not being the case).

Hmmmm, looking again at the issue, it seems like no tech people on FF's end has actually said anything.

Nice... I will go tell my clients to just wait until whenever and my bills... I will just throw them away...

**Comment by Alezanello** [comment]
Hello everyone,

A quick update regarding this issue: it has already been addressed by the engineering team. We’re now just waiting for the next production release, which is coming very soon!

Thank you for your patience, and we appreciate your understanding.

**Comment by carlosmachina** [comment]
> Hello everyone,
> 
> A quick update regarding this issue: it has already been addressed by the engineering team. We’re now just waiting for the next production release, which is coming very soon!
> 
> Thank you for your patience, and we appreciate your understanding.

Although I would like to thank you, @Alezanello for bringing some feedback, we're unfortunately talking about a completely breaking issue for the ones affected, that has been going for about 6 days now and, also unfortunately, "**very soon**" is vague to a level of disrespect to everyone involved.

I understand that is probably not you, personally, that came up with this response, or at least I would like to think that this vagueness was not your idea, but surely, you're able to understand the level of frustration and even business losses that are surrounding this problem.

I can't tell **very soon** to my clients and partners. Not freaking **AGAIN**

**Comment by bbeckford** [comment]
Just updated to the latest version of FF, `FlutterFlow v5.0.0+ released January 14, 2025` on Web and `FlutterFlow v5.0.20+ released January 14, 2025` on Windows - and this bug is **STILL** present - I hope it does not contain the promised fix above as it certainly did not fix the issue.

Please can we get an update with real dates in it @Alezanello? I've exhausted all borrowed time with my client now and I'm having to seek alternative solutions - which sadly may involve leaving FF altogether.

Identical to my first report:

![image](https://github.com/user-attachments/assets/0dd88f4f-32ff-4a11-a15b-8256b609c09e)

**Comment by bbeckford** [comment]
Just updated to the latest version of FF, `FlutterFlow v5.0.0+ released January 14, 2025` on Web and `FlutterFlow v5.0.20+ released January 14, 2025` on Windows - and this bug is **STILL** present - I hope it does not contain the promised fix above as it certainly did not fix the issue.

Please can we get an update with real dates in it @Alezanello? I've exhausted all borrowed time with my client now and I'm having to seek alternative solutions - which sadly may involve leaving FF altogether.

Identical to my first report:

![image](https://github.com/user-attachments/assets/0dd88f4f-32ff-4a11-a15b-8256b609c09e)

**Comment by gabrielbuarque** [comment]
The previous issue was resolved with the latest FlutterFlow update, but now the project won't run at all, and the error messages are inconsistent or unclear. Both Test Mode, Run Mode, and Deploy to Web fail, with a message asking me to check for errors in the project, but it doesn’t specify what’s wrong. Additionally, I can’t download the project code to debug it locally.

In FlutterFlow Desktop, I’m getting the following errors related to a custom function I haven’t modified, and that was previously working perfectly:

Custom Function:
"Custom functions need to be checked for errors. Click here to check for errors."

Function Code Errors:
"The body might complete normally, causing 'null' to be returned, but the return type, 'bool', is a potentially non-nullable type. Try adding either a return or a throw (Line 69, Character 6)."

The strange part is that my custom function only has 24 lines of code, yet the error points to line 69, which doesn’t exist.

When I run the project in the browser, this error in the custom function does not appear, but attempting to run Test Mode still results in a Build Failed message with no error code or additional details provided. I am completely stuck as the project won’t run in any mode, and downloading the code to debug locally isn’t possible either.

**Comment by syg-eliseu** [comment]
The error also persists for me after the January 14th update. When will they actually resolve it?

![image](https://github.com/user-attachments/assets/d897fc5f-8e8f-4612-b1af-36a2928146d6)

**Comment by bbeckford** [comment]
**_Still_** persists in `FlutterFlow v5.0.21+ released January 15, 2025`

**Comment by carlosmachina** [comment]
As @bbeckford stated, the problem still persists, with the same logs, even.

Now, let's talk a little, please. We're all devs here (as one would suppose) and as such, we do understand how terrible a situation like this can be.

With this, I beg you guys (on the FlutterFlow team): stop this swindle attempt.

Just be open, be honest.

> "Well, the problem is X, it will take 2 days for a new version..."

See, this wouldn't even stablish that in 2 days it would be a _solution_, just the newest try to address the issue. That would be very respectful of you. Or even:

> "See, we still have no idea where the problem is, but we're looking into Y, W and Z..."

The problem is severe, the lack of competent communication is aggravating. Please, guys, don't throw your name into the mud like this, there are better ways to deal with this situation, but it will not be the _mega corporation_ way of just saying "We are aware there are problems, and our team is working diligently to solve this issue as soon as possible".

You need to step up and show that all users, all people paying, working with, relying on and even celebrating FlutterFlow that you're a serious software endeavor that warrants trust and respect.

![image](https://github.com/user-attachments/assets/5537cf56-40b9-4221-b247-93bdeac0c6b9)

![image](https://github.com/user-attachments/assets/7be9f4ff-57b3-4d88-b51c-55b59c765d32)

**Comment by nathankrishnan** [comment]
Hi everyone, thank you for your patience and I want to assure you that we are actively addressing the issues. To recap, there are two issues for us to address here: [#5239](https://github.com/FlutterFlow/flutterflow-issues/issues/5239) (this one) and #5252.

We have fixes for these two issues and we are planning to release them next Tuesday (Jan 21). If it becomes feasible to release the fixes sooner, I will update here.

**Comment by bbeckford** [comment]
@nathankrishnan thank you for the update and for providing an actual date, it is very much appreciated. 

The 21st is unfortunately longer than one of my clients can wait, so I will have to seek a workaround for releasing a build, but at least we know now. 

In future it would be really helpful if you could provide timelines for critical bugs such as this early on, it helps us manage expectations within our businesses and builds trust in your tool.

Thanks

**Comment by syg-eliseu** [comment]
@bbeckford Look at my comment on another ticket, it was the way I managed to build my applications, I hope you help too.

https://github.com/FlutterFlow/flutterflow-issues/issues/5252#issuecomment-2586893805

**Comment by nathankrishnan** [comment]
Upon further analysis, there are two net new issues for us to track that are not related to the original issue reported. 

@carlosmachina can you please share the Bug Report Code for your project? The [screenshot](https://github.com/FlutterFlow/flutterflow-issues/issues/5239#issuecomment-2593619084) shared in your comment indicates a separate issue at compile time. We would like to investigate this.

@syg-eliseu, the recent screenshot [screenshot](https://github.com/FlutterFlow/flutterflow-issues/issues/5252#issuecomment-2592895614) you shared on [#5252](https://github.com/FlutterFlow/flutterflow-issues/issues/5252) is different than what @bbeckford reported. We are taking a look at this so we can determine how to resolve. 

To summarize:
- The original issue reported by @Mr-AT-Thompson in this ticket description is resolved and the fix is live.
- For the original issue reported by @bbeckford in [ticket 5252](https://github.com/FlutterFlow/flutterflow-issues/issues/5252) we have a fix prepared and are planning to release it live next week on Tuesday (Jan 21).
- The screenshot shared by @carlosmachina indicates a separate new issue (compile time issue). If you can please share your project's Bug Report Code, we can investigate this.
- The screenshot shared by @syg-eliseu in [ticket 5252](https://github.com/FlutterFlow/flutterflow-issues/issues/5252) also indicates a separate new issue. We are currently investigating this.

**Comment by bbeckford** [comment]
Thanks for the update @nathankrishnan

**Comment by carlosmachina** [comment]
@nathankrishnan, thank you for investigating those issues further, this is the bug report code provided by FF: 

```
ITFTlcn15ZNOmN9c+KrcKscwqCo4M0MdXOczitVEew4bCIj4PO0fduLeVFRVOdyzaHN+PmegmkIy0870jt+WUewrEyiYR4M51ZYBQxPPbF2uaZCwCKWBOXZfL+BYCEik3MKzkRZBKfhtWiEk3EyECOyQYz6Cf9qOYwx5e6fDbOY=
```

I'll be available for any other information needed to fully resolve this issue.

**Comment by nathankrishnan** [comment]
Thanks for sharing your bug report code @carlosmachina.
