### ISSUE TITLE
Unable to Validate Firestore Schema due to insufficient permissions.

### ISSUE THREAD

**Issue by KelpME** [FlutterFlow/flutterflow-issues#793]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

unable to Validate Firestore Schema due to insufficient permissions. Happening on all new projects and old.
![image](https://user-images.githubusercontent.com/100400724/233399239-ab272b9a-edf0-438b-9d3e-c773810704d4.png)

### Expected Behavior

Normal use of the Validate Schema button within flutterflow. 

### Steps to Reproduce

1. start new flutterflow project
2. start new firebase project
3. follow the instructions posted here (The flutterflow provided tutorial linked on the Firebase Project Setup page): https://www.youtube.com/watch?v=bG30uJ530-A
4. double check firestore rules are not in test mode. by using these rules:
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
5.make sure the service accound (firebase@flutterflow.io) is created and has the 'editor', 'Cloud Functions Admin', and 'Service Account User' Roles added.
6. double check a 'users' collection is created and has data in it within the firestore.
7. make sure the firestore is on a paid (blaze) plan.
8. link the firestore to the flutterflow project using the flutterflow wizard.
9. enable authentication and create a User Collection.
10. create a home page and landing page (blanks)
11. generate config files within flutterflow.
12. Try to Validate schema within flutterflow.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Context

I am unable to connect to firestore databases on any of my projects. I can confirm that billing within firebase is not the issue.

### Visual documentation

![image](https://user-images.githubusercontent.com/100400724/233404959-a1bd1364-2e90-45fb-9bbe-a28401863c1a.png)

![image](https://user-images.githubusercontent.com/100400724/233405638-75fb4fb1-c2d3-4f45-b4c7-bb820c6f6375.png)

### Additional Info

I have already been suggested the tutorial titles 'Unable to validate Firestore Schema: Unable to load data from collection. Missing or insufficient permissions' written by David. 

This includes checking these troubleshooting steps:
Troubleshooting Steps:
1. Make sure you already created a database in firebase
2. Make sure your database is not on TEST MODE. 
Important: A Database in Test Mode may not work properly

Note: after creating the database on test mode there is no visual way to set it on production mode, instead, you need to change the firebase rules. and if you deploy your rules from Flutterflow it will be done. and no need to do this manually and you can skip this part.

1) Go to your firebase project.

2) Select Cloud Firestore.

3) Select Rules.

Change it as follows, Note: mind the rules_version and ensure you are reflecting the correct rules_version.

4) Publish.

That's it, you are now switched to Production mode.  Thanks.

Tags: Firebase Cloud Firestore project

4. Make sure you give the necessary permissions to [firebase@flutterflow.io](mailto:firebase@flutterflow.io) editor account in your firebase project
 

You will need to add the following cloud permissions for [firebase@flutterflow.io](mailto:firebase@flutterflow.io): Editor, Cloud Functions Admin, and Service Account.

 

Head to the [Firebase Console](https://console.firebase.google.com/) and open the project dashboard for your project (click the project tile). Select Project Settings > Users & Permissions.

 

If you don't have Cloud Functions Admin, Editor, and Service Account listed next to [firebase@flutterflow.io](mailto:firebase@flutterflow.io), you have not completed this step.

 

[Here are the instructions](https://docs.flutterflow.io/firebase/firebase-setup#3.-enable-access-to-your-project) on how to add the required cloud permissions to your project.

5. Make sure you at least one collection created in FlutterFlow
Select the Firestore tab from the left menu. If you have no collections listed, you will need to create one.
[This article](https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/creating-collections) will walk you through step-by-step on how to create a collection.
6. Make sure that at least one of your collections has at least one document. 
You can use the CMS in FlutterFlow to confirm that you have at least one document. Select Manage Content and view your collections.
If you don't see any data listed, you will need to add this data.

[This article](https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/adding-data#1.-using-the-firestore-data-manager) will walk you through step-by-step on how to use the FlutterFlow CMS to add data to your collection.

7. Make sure you deployed your database rules with the proper permissions
From within your FlutterFlow project, select Firestore > Settings > Scroll down to Firestore Rules > select Deploy/Redploy.

### Environment

```markdown
- FlutterFlow version: Flutterflow V3.1 - Flutter 3.7.3
- Platform: Web
- Browser name and version: Brave Version 1.50.121 Chromium: 112.0.5615.138 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Home 22H2
```

**Comment by KelpME** [comment]
I believe this to be fixed by some means unbeknown to me. Thank you for your time and hard work!

![image](https://user-images.githubusercontent.com/100400724/233447905-168eb3a4-c842-41b3-9361-d8ef126b7991.png)

**Comment by andygrillo** [comment]
Did this just go away for you?

I suddenly today found the flutterflow can't access the user collection which has broken my app.

I also get the same message when validating:

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6279965/c1ff1ae0-7c9d-4c28-ac3a-f4c25fbb2029)

**Comment by andygrillo** [comment]
I posted in the forums some of the fixes I have tried:

I tried recreating config files, deleting firebase@flutterflow.io from auth users in firebase, adding app.flutterflow.io to auth domains in firebase, logging out, logging in, turning on/off user collection in FF.

When trying to validate teh schema it fails saying
'Unable to validate Firestore schema' unable to load data from colleciton:users.

I have firebase@flutterflow.io as a user in firebase project settings with the Editor, Cloud Functions Admin, and Service Account User roles (which worked yesterday).

**Comment by andygrillo** [comment]
@bulgariamitko please can you reopen this issue ? OP never found the cause of the issue, and I am now having the same problem. This has completely broken the app for all my users.

**Comment by askprateek** [comment]
Facing the same issue. 
I just switched to a new Firebase project. Repeated all the steps and still facing the issue.

**Comment by askprateek** [comment]
Fixed the issues.
- The error is because of the GCP deploy region of the Firebase Database 
- Make sure is `us-central`
- You will find this while creating a new firebase project.
<img width="392" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/9272830/3664050e-47a4-4ec6-b86c-38dfa55df6e2">

**Comment by Alexandre-Lemyre** [comment]
Hi. I am using my app in the context of a research project and the collected data absolutely need to be stored on servers in Canada (northamerica-northeast1). This is non-negotiable with our ethics committee. I cannot choose nam5 (US-central). This will be the same for other developers of apps who collect medical or otherwise sensitive data from outside the US.

**Comment by shrikant92** [comment]
In my case, the App check was restricting the schema validation. I unenforced the cloud firestore under App Check and it worked. Yet to figure out how to make it work without unenforcing the cloud firestore app check.

**Comment by weasel4o** [comment]
Whatever I do - I can't manage this. I have the same errors (fixed the validation, but still can't connect firestore properly). I give up. I'm going with another no-code provider.

**Comment by DanRoss88** [comment]
Copy Paste FlutterFlow rules into firestore rules. Worked for me.

**Comment by jessieplaydatecare** [comment]
Facing the same issue again, can we reopen this ticket

**Comment by hindichurch** [comment]
Facing this issue again. Initially the schema validation failed. And then when I redeployed the rules, and regenerated the firestore config files from settings, it gave this same "user" collection error. When I set the user collection permissions to "everyone" in everything, it gives a strange validation error. 

![Screenshot 2024-08-22 233830](https://github.com/user-attachments/assets/71a57b78-660b-4502-9f41-de2e8d896e34)
![Screenshot 2024-08-22 234043](https://github.com/user-attachments/assets/5608f352-4926-4d14-8c2d-1c15a596514f)

**Comment by divingjoker** [comment]
i have the same issue as well , even i create a blank new project with just users collection, still shows failed to validate firestore schema 

<img width="1254" alt="螢幕截圖 2024-08-23 17 42 50" src="https://github.com/user-attachments/assets/621efb2e-b96b-4373-84e0-62ed1ff10c39">
