### ISSUE TITLE
Google maps: zoom in/out and tool bar not working

### ISSUE THREAD

**Issue by loohelen** [FlutterFlow/flutterflow-issues#900]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Only zoom in using tap and showing user location work.
The following does not work: zoom in/out buttons.
Map toolbar shows up but does not open the Maps app nor directions.

### Expected Behavior

Be able to use zoom in/out buttons.
Be able to use zoom in/out using touch.
Seeing the Map toolbar to open Maps / directions.
When clicking the marker, being able to get directions to it, or open it in the Maps app.

### Steps to Reproduce

Create a Google Maps widget
Enable the following features:
- Allow interacting with the Map
- Allow zooming the Map
- Show user location
- Show Map Toolbar
Create a marker
- Add marker to map

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89grswC+qqJY+5AhQMnQzM5U+cFjtt+Zw8hfLbmPewyfMykZRJLYtezegpPelmYmnoy087zjuHPO/ECHxyeGq46zq5XQQHKTmORV66UO6uWSUF7N5lRfUeO4cKjrxUnKuNhWngg2nGmIvCrG3qCf9qOYwx5e6fDbOY=

### Context

I am trying to present a map with markers, which the users can select. The lack of zoom in/out, and lack of directions make the map somewhat useless

### Visual documentation

Screen recording:
https://github.com/FlutterFlow/flutterflow-issues/assets/52323333/def76898-d8a3-49e5-982b-691712487f31

### Environment

```markdown
- FlutterFlow version: 3.1, Flutter 3.7.12
- Platform: Android
- Browser name and version: N/A
- Operating system and version affected: tested on Android 13
```

**Comment by loohelen** [comment]
This issue is resolved by updating the Google Maps flutter packages' versions:
-   google_maps: 6.3.0
-   google_maps_flutter: 2.2.6
-   google_maps_flutter_platform_interface: 2.2.6
-   google_maps_flutter_web: 0.4.0+8

**Comment by wenkaifan0720** [comment]
Hi @loohelen. Thank you so much for taking the time and found the fix. We will update our google map dependencies in our next update. I'll close this issue for now.

**Comment by loohelen** [comment]
Showing user location no longer works, even with the updated packages. Can you please reopen this issue?

**Comment by Fibn007** [comment]
Hi @wenkaifan0720, this issue is not fixed. In iOS, when using Google Maps and selecting "Show Zoom buttons on the Map", the Zoom buttons do not show up. Also, when selecting "Allow zooming the map" it takes a lot of tries to actually zoom in and out while pinching my fingers. I can successfully do it once every 20 attempts. My setup is attached in the picture:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/11437500-7b9e-4c0c-a855-4fad850e3f75)

**Comment by carmenchargely** [comment]
Hi, I'm also experiencing this issue. The Zoom buttons appear on Android but not iOS. You can double tap to zoom on iOS, but not all of our users will know to do that.

See attached screen recordings:
Google Maps zoom working on Android:
https://github.com/FlutterFlow/flutterflow-issues/assets/136000563/d7b87e3a-f3a0-475e-be0e-6d418ff2c166

Google Maps zoom buttons not appearing on iOS:
https://github.com/FlutterFlow/flutterflow-issues/assets/136000563/d29f5f54-5422-4eeb-b06c-c71d989a4269

**Comment by wenkaifan0720** [comment]
Hi @carmenchargely. Sorry for the delayed response. I didn't deal with this issue because I knew we are using the latest version of the `google_maps_flutter` package. Today I went into the actual code and was trying to see what we can do and found this comment:
```
  /// True if the map view should show zoom controls. This includes two buttons
  /// to zoom in and zoom out. The default value is to show zoom controls.
  ///
  /// This is only supported on Android. And this field is silently ignored on iOS.
  final bool zoomControlsEnabled;
```

There's not much we can do until the flutter team updates this package to support zoom on iOS. I will close this issue for now.
