### ISSUE TITLE
TextField blank the page when open keyboard on real device

### ISSUE THREAD

**Issue by corsaro0** [FlutterFlow/flutterflow-issues#921]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The problem occurs only if the page has navbar.

On a real device (i use android pixel 7), when i open the keyboard to type, a band appears that covers an equal space of the keyboard.

### Expected Behavior

When click on textfield i can see the page without blocking element

### Steps to Reproduce

1. create a page with navbar (i used floating navbar)
2. insert a textflied
3. Download APK and test on real device
4. click texfield and open keyboard

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTl8nf5ZZ1rsNc+KX1K/pvr2QQI0McX5Ir1utsewgjGKL1Bu02d+DRZRdDXuGraVNfelWamjsCweiMjobDNvdeIROYbYA6walqSAree2ihVpC1PKrhPXNfGZ5Uf2KG4KWjnyYnH7FsWEI+2lOQN+6tcHbDFOu/Zwh9f6PHaOI=

### Context

I'm trying to make a form for posting

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/129213503/49d64d0b-de87-4da9-8f81-4bbe419d7e5d

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: 
- Browser name and version: chrome
- Operating system and version affected: Android and Windows
```

**Comment by paulVu** [comment]
Please share hot fix

**Comment by hariprasadms** [comment]
Hi @corsaro0 - Thanks for submitting the issue. I can re-produce the issue. This bug is happening when Nav Bar Style type is **'Floating nav bar'**. For other nav bar type it works fine. 

I also noticed that, when Nav Bar style is **'Floating nav bar'**, in test mode, nav bar icons does not show up its active and inactive colours. Can you please check is this happening for your project as well ?

Thanks

**Comment by sgrprabhu** [comment]
@hariprasadms , the navbar issue as shown in your video was there a week ago but now gone (it was randomly happening then). Also, the keyboard issue from https://github.com/FlutterFlow/flutterflow-issues/issues/926 yesterday also goes away when the navbar is changed from floating to flutter default. Apparently, the screens without the keyboard issue were without navbars!

**Comment by hariprasadms** [comment]
Thanks for confirming the issue @sgrprabhu @corsaro0. However, we will look at this and see what fix we can do. Thanks

**Comment by paulVu** [comment]
Thank @hariprasadms that's work.

**Comment by agreaves** [comment]
Hi @corsaro0, @paulVu and all, thank you very much for the bug report and information. We've identified the issue, it is indeed the change seen in #926, which was intended to fix another small bug for floating nav bar. This bug is much bigger so we will revert for now and address that issue later.

This should be fixed in the upcoming release!

**Comment by Franco98404** [comment]
Hello @agreaves and @hariprasadms. I still have this problem

https://www.loom.com/share/15ac0cf69dcb4983864e677536a8188c?sid=3bf3ebc2-4a94-431c-9432-963b787c30d6

As you can see the problem is not consistent

**Comment by Franco98404** [comment]
Hello @paulperez-dev @rzambroni @leighajarett, can you check this issue please? Still happening

**Comment by leighajarett** [comment]
@Franco98404 I am having trouble reproducing this issue. Can you file a new issue with steps to reproduce from a blank project? Thanks so much!

**Comment by Franco98404** [comment]
> @Franco98404 I am having trouble reproducing this issue. Can you file a new issue with steps to reproduce from a blank project? Thanks so much!

Hello @leighajarett, trying to replicate the bug was difficult, but I could do it!

The first step is building in FF
https://www.loom.com/share/44b3d9794aad4ef8acf6cac55da78ada

Testing on Android device (Web)
https://www.loom.com/share/9300b918794742089f4c680f64e5aea0

Hope this can be useful to solve the bug

**Comment by ryanc4ai** [comment]
This bug is impacting me as well.

Extra space added when the keyboard is activated of a text input in the lower 30% of the screen.

This only happens on Web on Mobile (native apps don't insert the extra space).

I made a test project to show this. Focus into each of the text inputs, the lower 2 show the issue:
https://test-scrollable-j8rcgt.flutterflow.app/
https://app.flutterflow.io/project/test-scrollable-j8rcgt?tab=uiBuilder&page=HomePage

**Comment by Franco98404** [comment]
@ryanc4ai It looks like you were able to replicate the problem easier than me, I hope FF fixes it soon!
