### ISSUE TITLE
Design Library missing

### ISSUE THREAD

**Issue by spiralventures** [FlutterFlow/flutterflow-issues#959]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The design library options including Figma import no longer appear on the design system page.

### Expected Behavior

There should be a design library option and Figma import button according to the documentation here https://docs.flutterflow.io/widgets-and-components/theme-settings/design-system

### Steps to Reproduce

Go to the design system settings page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kz/Hqx89god9c18/Ud8Fr/SoQKUR/U4JNlsIbbAI3fb7pG7YAW/SkQE9WZ7yhdH03PGeguH0e06mMudzIN/YoKSubbpRAwap+bQnyJUCmRLquPJGCdGhBJNpKBW6X4baJmApDHMRpS1Y/wGa2C/PKYz/fK5f6IVcZRM+LMZLAs3/uQ0SLb3kNh1JWeC/v

### Context

Trying to use a design library and import figma too. I've had to recreate 20+ colors for both light and dark mode in order to use the design library I want to use and can't reuse for other projects because this feature isn't available.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/124305096/035cb3e4-8917-48d2-a637-aae8b9167af6)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Version 114.0.5735.91 (Official Build) (64-bit)
- Operating system and version affected: Windows 11
```

**Comment by SameerShahzad99** [comment]
Hi @spiralventures, Thank you for reporting this issue.
It appears to be showing up fine on my end, Can you please confirm if you are still facing this issue?
![SCR-20230603-issr](https://github.com/FlutterFlow/flutterflow-issues/assets/126883330/6bb44b5c-5678-42c5-a2f5-28e4276341e2)

**Comment by HeikoKanzler** [comment]
Same here. The design system functionality is gone since one of the last updates.
This is not project specific.
Many reports in the community, too.

Please review and escalate

**Comment by spiralventures** [comment]
@SameerShahzad99 it's still not showing up. Since it's not project specific and doesn't seem to be happening for everyone my guess it might be due to our account, either the plan where on or how old our plan is, if there were any changes and we weren't migrated or are missing a value that newer users get assigned when signing up??

It's very strange, especially since your screenshot is missing the Figma import option too.

**Comment by HeikoKanzler** [comment]
I just created a small team of two, those accounts do have the design system button, but not the Figma-import button.

Both features have been available on my private account until one of the recent updates.

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue. It should be fixed now.

**Comment by spiralventures** [comment]
@aemelyanovff the figma import is showing, going off what HeikoKanzler mentioned I created a team and then the design system button appeared, so may want to update the documentation to highlight that having a team setup (even if it's not used or have any members) is a prerequisite for the design system function to be used.

**Comment by Neve3783** [comment]
Hi - I am a new user and while this post is from last year, I am having the same problem with the project I started less then a month ago based on the DreamBrush Template.

I see the Figma import option but no way to create a design library. I tried the suggestion mentioned above and invited a collaborator but this did not solve the issue.

I would really appreciate any help you can give me as I’ve already spent a lot of time on this project. Thank you.
<img width="1530" alt="Screenshot 2024-12-09 at 4 09 37 PM" src="https://github.com/user-attachments/assets/f963d07f-c7c8-4e82-b602-f47bfd07cbad">

**Comment by emrehlc** [comment]
> Thanks for reporting the issue. It should be fixed now.

It's not fixed.
